import { DxcBulletedList, DxcFlex, DxcParagraph } from "@dxc-technology/halstack-react";
import QuickNavContainer from "@/common/QuickNavContainer";
import DocFooter from "@/common/DocFooter";
import Image from "@/common/Image";
import anatomy from "./images/chip-anatomy.png";
import dismissible from "./images/dismissible-chip.png";
import selectable from "./images/selectable-chip.png";
import selectableExample from "./images/selectable-example.png";
import dismissibleExample from "./images/dismissible-example.png";

const sections = [
  {
    title: "Introduction",
    content: (
      <>
        <DxcParagraph>
          Chips help users quickly scan, organize, and interact with content by surfacing relevant items in a clear and
          lightweight way.
        </DxcParagraph>
        <DxcParagraph>
          They are commonly used to support filtering, categorization, and selection workflows, or to display values
          generated by user input such as search terms, selected options, or attached items. Chips are typically
          displayed in groups and are designed to work alongside other interface elements such as inputs, filters, lists
          and data views, depending on the variant and use case.
        </DxcParagraph>
      </>
    ),
  },
  {
    title: "Anatomy",
    content: (
      <>
        <Image src={anatomy} alt="Chip anatomy" />
        <DxcBulletedList type="number">
          <DxcBulletedList.Item>
            <strong>Container</strong>: it's the area that holds the chip’s content, defining its shape, size, spacing
            and interactive states (if applicable) of the component.
          </DxcBulletedList.Item>
          <DxcBulletedList.Item>
            <strong>Left Element</strong>: an optional visual element displayed before the label. It can be an icon or
            an avatar used to provide additional context or help users quickly identify the content.
          </DxcBulletedList.Item>
          <DxcBulletedList.Item>
            <strong>Label</strong>: displays the textual content of the chip, conveying selection, user input or key
            filtering data.
          </DxcBulletedList.Item>
          <DxcBulletedList.Item>
            <strong>Dismiss action</strong>: an action control that allows users to remove the chip from the interface
            and it’s only present in the dismissible variant of the component.
          </DxcBulletedList.Item>
        </DxcBulletedList>
      </>
    ),
  },
  {
    title: "Variants",
    content: (
      <DxcParagraph>
        Depending on how it is used within an interface, the chip component can take two different forms:{" "}
        <strong>selectable chip</strong> and <strong>dismissible chip</strong>. Each variant supports a different
        interaction pattern and serves a distinct purpose in the interface.
      </DxcParagraph>
    ),
    subSections: [
      {
        title: "Selectable chip",
        content: (
          <>
            <Image src={selectable} alt="Selectable chip" />
            <DxcParagraph>
              The selectable chip is an interactive element that allows users to{" "}
              <strong>activate or clear options directly within the interface</strong>. It is commonly used to filter
              content, highlight categories or trigger lightweight actions without requiring additional controls such as
              dropdowns or menus. Selectable chips are typically displayed in groups, allowing users to quickly adjust
              the information shown on the screen or interact with specific items.
            </DxcParagraph>

            <DxcParagraph>
              Selectable chips can include an optional <strong>left element</strong>, which may be either an icon or an
              avatar, used to visually reinforce the meaning of the chip. Depending on the context, the chip can be
              displayed in different configurations:
            </DxcParagraph>

            <DxcBulletedList>
              <DxcBulletedList.Item>
                <strong>Icon / Avatar + label</strong>, when the left element helps reinforce the meaning of the label.
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Icon only</strong>, when the icon is sufficiently descriptive on its own.
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Label only</strong>, when additional visual context is not required.
              </DxcBulletedList.Item>
            </DxcBulletedList>

            <DxcParagraph>
              This flexibility allows selectable chips to adapt to different layouts and levels of visual density. This
              variant of the chip is often used in situations where users need to quickly explore or organize
              information without navigating away from the current view.
            </DxcParagraph>
            <DxcParagraph>
              <strong>Use cases</strong>:
            </DxcParagraph>

            <DxcBulletedList>
              <DxcBulletedList.Item>
                <strong>Filtering content within a page</strong>, such as refining results in a table, list or dashboard
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Segmenting groups of content</strong>, for example switching between conversation categories in
                a messaging interface
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Highlighting attributes or tags</strong> that help organize large sets of information
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Triggering contextual actions</strong>, such as marking an item as a favorite or indicating a
                preference
              </DxcBulletedList.Item>
            </DxcBulletedList>
            <Image src={selectableExample} alt="Selectable chip example" />
          </>
        ),
      },
      {
        title: "Dismissible chip",
        content: (
          <>
            <Image src={dismissible} alt="Dismissible chip" />
            <DxcParagraph>
              The dismissible chip is used to{" "}
              <strong>represent information generated by user input within an interface</strong>. It commonly appears
              after a user performs an action, such as entering search terms, selecting values from another component or
              attaching files. In this variant, <strong>the chip serves as a visual representation</strong> of the input
              provided by the user.
            </DxcParagraph>

            <DxcParagraph>
              Unlike selectable chips, dismissible chips are <strong>not interactive elements by themselves</strong>.
              Their purpose is to display information that has already been applied or added. The only interactive
              element in this variant is the <strong>dismiss action</strong>, which allows users to remove the chip and
              clear the corresponding value or item.
            </DxcParagraph>

            <DxcParagraph>
              Dismissible chips always include a <strong>label</strong>, which describes the value, term, or item being
              represented. They also include a <strong>dismiss action</strong>, represented by a close icon, that
              enables users to remove the chip from the interface. An optional <strong>left element</strong>, such as an
              icon or avatar, can be included to provide additional context when needed.
            </DxcParagraph>

            <DxcParagraph>
              This variant is typically used in situations where users need to clearly see and manage the values they
              have entered or selected.
            </DxcParagraph>

            <DxcParagraph>
              <strong>Use cases</strong>:
            </DxcParagraph>

            <DxcBulletedList>
              <DxcBulletedList.Item>
                <strong>Displaying search terms</strong> entered by the user in a search field
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Representing applied filters</strong> that originate from other components such as selects or
                filter panels
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Showing selected values</strong> from inputs such as multi-select fields
              </DxcBulletedList.Item>
              <DxcBulletedList.Item>
                <strong>Displaying attached items</strong>, such as documents or files added to a form or message
              </DxcBulletedList.Item>
            </DxcBulletedList>

            <Image src={dismissibleExample} alt="Dismissible chip example" />
          </>
        ),
      },
    ],
  },
  {
    title: "Best practices",
    subSections: [
      {
        title: "General",
        content: (
          <DxcBulletedList>
            <DxcBulletedList.Item>
              <strong>Use chips to represent lightweight interactions</strong>. Chips should simplify common tasks such
              as filtering, categorizing or representing input without introducing additional complexity.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Display chips in groups when possible</strong>. Chips are easier to understand when presented
              alongside related options or values.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Use consistent labeling across chips</strong>. When chips appear together, labels should follow
              the same naming pattern to improve readability and comprehension.
            </DxcBulletedList.Item>
          </DxcBulletedList>
        ),
      },
      {
        title: "Selectable chip",
        content: (
          <DxcBulletedList>
            <DxcBulletedList.Item>
              <strong>Use selectable chips for lightweight filtering or categorization</strong>. They are most effective
              when helping users quickly refine or organize visible content.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Group related chips together</strong>. Selectable chips should usually appear in clusters that
              represent related categories or options.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Avoid using selectable chips for mutually exclusive options with strict selection rules</strong>.
              In cases where one option must always remain selected, the correct component to use is our toggle group.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Use icons or avatars only when they add meaningful context</strong>. Decorative elements should
              reinforce the meaning of the chip rather than duplicate the label.
            </DxcBulletedList.Item>
          </DxcBulletedList>
        ),
      },
      {
        title: "Dismissible chip",
        content: (
          <DxcBulletedList>
            <DxcBulletedList.Item>
              <strong>Use dismissible chips to represent user-generated input</strong>. They should display values that
              the user has entered, selected or added through other components.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Always provide a clear and accessible dismiss action</strong>. Users should be able to easily
              remove chips when they want to clear a value or undo an action.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Ensure the label clearly represents the value or item</strong>. The label should make it easy for
              users to understand what information the chip represents.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Place dismissible chips close to the input that generated them</strong>. This helps users
              understand the relationship between the chip and the original action.
            </DxcBulletedList.Item>
            <DxcBulletedList.Item>
              <strong>Use icons or avatars only when they provide additional context</strong>. For example, icons can
              help represent file types, categories or other recognizable items.
            </DxcBulletedList.Item>
          </DxcBulletedList>
        ),
      },
    ],
  },
];

const ChipOverviewPage = () => (
  <DxcFlex direction="column" gap="4rem">
    <QuickNavContainer sections={sections} startHeadingLevel={2} />
    <DocFooter githubLink="https://github.com/dxc-technology/halstack-react/blob/master/apps/website/screens/components/chip/overview/ChipOverviewPage.tsx" />
  </DxcFlex>
);
export default ChipOverviewPage;
