export const coreTokens: Record<string, string | number> = {
  /**************/
  /** POSITION **/
  /**************/

  /* Application Layout */
  "--z-app-layout-sidenav": 100,
  "--z-app-layout-header": 110,

  /* Header */
  "--z-header-overlay": 200,
  "--z-header-menu": 210,

  /* UI components */
  "--z-date-input": 300,
  "--z-dropdown": 310,
  "--z-textinput": 320,
  "--z-select": 330,
  "--z-contextualmenu": 340,

  /* Modals and overlays */
  "--z-dialog": 400,
  "--z-spinner-overlay": 410,
  "--z-progressbar-overlay": 420,
  "--z-alert": 430,

  /* Notifications */
  "--z-toast": 500,

  /* Tooltip (topmost) */
  "--z-tooltip": 600,

  /************/
  /** TOKENS **/
  /************/

  /* Core tokens */
  "--color-absolutes-black": "#000000",
  "--color-absolutes-white": "#ffffff",
  "--color-alpha-100-a": "#e1e2e41a",
  "--color-alpha-200-a": "#d5d5d933",
  "--color-alpha-300-a": "#c8c8cc4d",
  "--color-alpha-400-a": "#adadb466",
  "--color-alpha-500-a": "#92939b80",
  "--color-alpha-600-a": "#72737e99",
  "--color-alpha-700-a": "#545662b2",
  "--color-alpha-800-a": "#414250cc",
  "--color-alpha-900-a": "#2b2d3ce5",
  "--color-primary-50": "#f1f1f9",
  "--color-primary-100": "#e0e1f3",
  "--color-primary-200": "#d2d3ed",
  "--color-primary-300": "#c5c7e8",
  "--color-primary-400": "#a6aadb",
  "--color-primary-500": "#878fcf",
  "--color-primary-600": "#5c6fbf",
  "--color-primary-700": "#2351b0",
  "--color-primary-800": "#003c9b",
  "--color-primary-900": "#00247c",
  "--color-secondary-50": "#ffeee7",
  "--color-secondary-100": "#ffdacb",
  "--color-secondary-200": "#fecab5",
  "--color-secondary-300": "#fbba9f",
  "--color-secondary-400": "#f29770",
  "--color-secondary-500": "#e57443",
  "--color-secondary-600": "#cf4400",
  "--color-secondary-700": "#a82000",
  "--color-secondary-800": "#8d0000",
  "--color-secondary-900": "#640000",
  "--color-tertiary-50": "#fef1c7",
  "--color-tertiary-100": "#f8e288",
  "--color-tertiary-200": "#eed557",
  "--color-tertiary-300": "#e1c94c",
  "--color-tertiary-400": "#c3ae2f",
  "--color-tertiary-500": "#a7940c",
  "--color-tertiary-600": "#837400",
  "--color-tertiary-700": "#625600",
  "--color-tertiary-800": "#4e4400",
  "--color-tertiary-900": "#392c00",
  "--color-semantic01-50": "#e9f2fb",
  "--color-semantic01-100": "#d1e5f6",
  "--color-semantic01-200": "#bcd9f2",
  "--color-semantic01-300": "#a6ceee",
  "--color-semantic01-400": "#70b5e5",
  "--color-semantic01-500": "#159ddb",
  "--color-semantic01-600": "#007ab6",
  "--color-semantic01-700": "#005991",
  "--color-semantic01-800": "#00457b",
  "--color-semantic01-900": "#002d60",
  "--color-semantic02-50": "#e7f5eb",
  "--color-semantic02-100": "#cde9d5",
  "--color-semantic02-200": "#b8dfc5",
  "--color-semantic02-300": "#a0d5b2",
  "--color-semantic02-400": "#6cbe8c",
  "--color-semantic02-500": "#2aa868",
  "--color-semantic02-600": "#008548",
  "--color-semantic02-700": "#00642a",
  "--color-semantic02-800": "#005018",
  "--color-semantic02-900": "#003700",
  "--color-semantic03-50": "#ffefda",
  "--color-semantic03-100": "#ffddb1",
  "--color-semantic03-200": "#ffcd8d",
  "--color-semantic03-300": "#ffbc66",
  "--color-semantic03-400": "#ec9d2f",
  "--color-semantic03-500": "#cd840d",
  "--color-semantic03-600": "#a76400",
  "--color-semantic03-700": "#834700",
  "--color-semantic03-800": "#6d3300",
  "--color-semantic03-900": "#541c00",
  "--color-semantic04-50": "#ffede7",
  "--color-semantic04-100": "#ffdad0",
  "--color-semantic04-200": "#ffc9bb",
  "--color-semantic04-300": "#ffb8a6",
  "--color-semantic04-400": "#fe8f75",
  "--color-semantic04-500": "#f4674b",
  "--color-semantic04-600": "#df2a19",
  "--color-semantic04-700": "#b10000",
  "--color-semantic04-800": "#8d0000",
  "--color-semantic04-900": "#640000",
  "--color-neutral-50": "#f1f1f2",
  "--color-neutral-100": "#e1e2e4",
  "--color-neutral-200": "#d5d5d9",
  "--color-neutral-300": "#c8c8cc",
  "--color-neutral-400": "#adadb4",
  "--color-neutral-500": "#92939b",
  "--color-neutral-600": "#72737e",
  "--color-neutral-700": "#545662",
  "--color-neutral-800": "#414250",
  "--color-neutral-900": "#2b2d3c",
  "--dimensions-0": "0px",
  "--dimensions-1": "1px",
  "--dimensions-2": "2px",
  "--dimensions-4": "4px",
  "--dimensions-8": "8px",
  "--dimensions-12": "12px",
  "--dimensions-16": "16px",
  "--dimensions-20": "20px",
  "--dimensions-24": "24px",
  "--dimensions-28": "28px",
  "--dimensions-32": "32px",
  "--dimensions-36": "36px",
  "--dimensions-40": "40px",
  "--dimensions-44": "44px",
  "--dimensions-48": "48px",
  "--dimensions-56": "56px",
  "--dimensions-64": "64px",
  "--dimensions-72": "72px",
  "--dimensions-80": "80px",
  "--dimensions-96": "96px",
  "--font-size-12": "12px",
  "--font-size-14": "14px",
  "--font-size-16": "16px",
  "--font-size-18": "18px",
  "--font-size-20": "20px",
  "--font-size-24": "24px",
  "--font-size-32": "32px",
  "--font-size-40": "40px",
  "--font-size-48": "48px",
  "--font-size-60": "60px",
  "--font-weight-light": "300",
  "--font-weight-regular": "400",
  "--font-weight-semibold": "600",
  "--font-weight-bold": "700",
  "--font-family-mono": "Source Code Pro, mono",
  "--font-family-sans": "Open Sans, sans-serif",
  "--font-style-lightitalic": "light italic",
  "--font-style-normal": "normal",
  "--line-style-dashed": "dashed",
  "--line-style-solid": "solid",
};

export const aliasTokens: Record<string, string | number> = {
  /************/
  /** TOKENS **/
  /************/

  /* Alias tokens */
  "--border-color-info-lightest": "var(--color-semantic01-50)",
  "--border-color-info-lighter": "var(--color-semantic01-100)",
  "--border-color-info-light": "var(--color-semantic01-200)",
  "--border-color-info-medium": "var(--color-semantic01-300)",
  "--border-color-info-strong": "var(--color-semantic01-600)",
  "--border-color-info-stronger": "var(--color-semantic01-700)",
  "--border-color-info-strongest": "var(--color-semantic01-800)",
  "--border-color-success-light": "var(--color-semantic02-300)",
  "--border-color-success-medium": "var(--color-semantic02-600)",
  "--border-color-warning-light": "var(--color-semantic03-300)",
  "--border-color-warning-medium": "var(--color-semantic03-500)",
  "--border-color-warning-strong": "var(--color-semantic03-600)",
  "--border-color-error-light": "var(--color-semantic04-300)",
  "--border-color-error-medium": "var(--color-semantic04-600)",
  "--border-color-error-strong": "var(--color-semantic04-700)",
  "--border-color-error-stronger": "var(--color-semantic04-800)",
  "--border-color-neutral-bright": "var(--color-neutral-50)",
  "--border-color-neutral-brighter": "var(--color-absolutes-white)",
  "--border-color-neutral-dark": "var(--color-neutral-900)",
  "--border-color-neutral-light": "var(--color-neutral-300)",
  "--border-color-neutral-lighter": "var(--color-neutral-200)",
  "--border-color-neutral-lightest": "var(--color-neutral-100)",
  "--border-color-neutral-medium": "var(--color-neutral-400)",
  "--border-color-neutral-strong": "var(--color-neutral-500)",
  "--border-color-neutral-stronger": "var(--color-neutral-600)",
  "--border-color-neutral-strongest": "var(--color-neutral-700)",
  "--border-color-primary-light": "var(--color-primary-400)",
  "--border-color-primary-lighter": "var(--color-primary-300)",
  "--border-color-primary-medium": "var(--color-primary-500)",
  "--border-color-primary-strong": "var(--color-primary-600)",
  "--border-color-primary-stronger": "var(--color-primary-700)",
  "--border-color-secondary-light": "var(--color-secondary-300)",
  "--border-color-secondary-medium": "var(--color-secondary-500)",
  "--border-color-secondary-strong": "var(--color-secondary-600)",
  "--border-color-secondary-stronger": "var(--color-secondary-700)",
  "--border-color-secondary-strongest": "var(--color-secondary-800)",
  "--color-bg-overlay-dark": "var(--color-alpha-800-a)",
  "--color-bg-yellow-light": "var(--color-tertiary-100)",
  "--color-bg-alpha-light": "var(--color-alpha-300-a)",
  "--color-bg-alpha-medium": "var(--color-alpha-800-a)",
  "--color-bg-alpha-strong": "var(--color-alpha-900-a)",
  "--color-bg-neutral-light": "var(--color-neutral-100)",
  "--color-bg-neutral-lighter": "var(--color-neutral-50)",
  "--color-bg-neutral-lightest": "var(--color-absolutes-white)",
  "--color-bg-neutral-medium": "var(--color-neutral-200)",
  "--color-bg-neutral-strong": "var(--color-neutral-300)",
  "--color-bg-neutral-stronger": "var(--color-neutral-800)",
  "--color-bg-neutral-strongest": "var(--color-neutral-900)",
  "--color-bg-primary-light": "var(--color-primary-200)",
  "--color-bg-primary-lighter": "var(--color-primary-100)",
  "--color-bg-primary-lightest": "var(--color-primary-50)",
  "--color-bg-primary-medium": "var(--color-primary-300)",
  "--color-bg-primary-strong": "var(--color-primary-700)",
  "--color-bg-primary-stronger": "var(--color-primary-800)",
  "--color-bg-primary-strongest": "var(--color-primary-900)",
  "--color-bg-secondary-light": "var(--color-secondary-200)",
  "--color-bg-secondary-lighter": "var(--color-secondary-100)",
  "--color-bg-secondary-lightest": "var(--color-secondary-50)",
  "--color-bg-secondary-medium": "var(--color-secondary-300)",
  "--color-bg-secondary-strong": "var(--color-secondary-600)",
  "--color-bg-secondary-stronger": "var(--color-secondary-700)",
  "--color-bg-secondary-strongest": "var(--color-secondary-800)",
  "--color-bg-info-lightest": "var(--color-semantic01-50)",
  "--color-bg-info-lighter": "var(--color-semantic01-100)",
  "--color-bg-info-light": "var(--color-semantic01-200)",
  "--color-bg-info-medium": "var(--color-semantic01-300)",
  "--color-bg-info-strong": "var(--color-semantic01-600)",
  "--color-bg-info-stronger": "var(--color-semantic01-700)",
  "--color-bg-info-strongest": "var(--color-semantic01-800)",
  "--color-bg-success-light": "var(--color-semantic02-200)",
  "--color-bg-success-lighter": "var(--color-semantic02-100)",
  "--color-bg-success-lightest": "var(--color-semantic02-50)",
  "--color-bg-success-medium": "var(--color-semantic02-300)",
  "--color-bg-success-strong": "var(--color-semantic02-600)",
  "--color-bg-success-stronger": "var(--color-semantic02-700)",
  "--color-bg-success-strongest": "var(--color-semantic02-800)",
  "--color-bg-warning-light": "var(--color-semantic03-200)",
  "--color-bg-warning-lighter": "var(--color-semantic03-100)",
  "--color-bg-warning-lightest": "var(--color-semantic03-50)",
  "--color-bg-warning-medium": "var(--color-semantic03-300)",
  "--color-bg-warning-strong": "var(--color-semantic03-500)",
  "--color-bg-warning-stronger": "var(--color-semantic03-600)",
  "--color-bg-warning-strongest": "var(--color-semantic03-700)",
  "--color-bg-error-light": "var(--color-semantic04-200)",
  "--color-bg-error-lighter": "var(--color-semantic04-100)",
  "--color-bg-error-lightest": "var(--color-semantic04-50)",
  "--color-bg-error-medium": "var(--color-semantic04-300)",
  "--color-bg-error-strong": "var(--color-semantic04-600)",
  "--color-bg-error-stronger": "var(--color-semantic04-700)",
  "--color-bg-error-strongest": "var(--color-semantic04-800)",
  "--color-fg-info-lightest": "var(--color-semantic01-50)",
  "--color-fg-info-lighter": "var(--color-semantic01-100)",
  "--color-fg-info-light": "var(--color-semantic01-200)",
  "--color-fg-info-medium": "var(--color-semantic01-300)",
  "--color-fg-info-strong": "var(--color-semantic01-600)",
  "--color-fg-info-stronger": "var(--color-semantic01-700)",
  "--color-fg-info-strongest": "var(--color-semantic01-800)",
  "--color-fg-success-light": "var(--color-semantic02-300)",
  "--color-fg-success-lighter": "var(--color-semantic02-200)",
  "--color-fg-success-medium": "var(--color-semantic02-600)",
  "--color-fg-success-strong": "var(--color-semantic02-700)",
  "--color-fg-success-stronger": "var(--color-semantic02-800)",
  "--color-fg-warning-light": "var(--color-semantic03-300)",
  "--color-fg-warning-medium": "var(--color-semantic03-500)",
  "--color-fg-warning-strong": "var(--color-semantic03-600)",
  "--color-fg-warning-stronger": "var(--color-semantic03-800)",
  "--color-fg-error-light": "var(--color-semantic04-300)",
  "--color-fg-error-lighter": "var(--color-semantic04-200)",
  "--color-fg-error-medium": "var(--color-semantic04-600)",
  "--color-fg-error-strong": "var(--color-semantic04-700)",
  "--color-fg-error-stronger": "var(--color-semantic04-800)",
  "--color-fg-neutral-bright": "var(--color-absolutes-white)",
  "--color-fg-neutral-dark": "var(--color-neutral-900)",
  "--color-fg-neutral-light": "var(--color-neutral-400)",
  "--color-fg-neutral-lighter": "var(--color-neutral-200)",
  "--color-fg-neutral-lightest": "var(--color-neutral-100)",
  "--color-fg-neutral-medium": "var(--color-neutral-500)",
  "--color-fg-neutral-strong": "var(--color-neutral-600)",
  "--color-fg-neutral-stronger": "var(--color-neutral-700)",
  "--color-fg-neutral-strongest": "var(--color-neutral-800)",
  "--color-fg-neutral-yellow-dark": "var(--color-tertiary-800)",
  "--color-fg-primary-light": "var(--color-primary-300)",
  "--color-fg-primary-lighter": "var(--color-primary-100)",
  "--color-fg-primary-medium": "var(--color-primary-400)",
  "--color-fg-primary-strong": "var(--color-primary-700)",
  "--color-fg-primary-stronger": "var(--color-primary-800)",
  "--color-fg-primary-strongest": "var(--color-primary-900)",
  "--color-fg-secondary-light": "var(--color-secondary-500)",
  "--color-fg-secondary-lighter": "var(--color-secondary-300)",
  "--color-fg-secondary-medium": "var(--color-secondary-600)",
  "--color-fg-secondary-strong": "var(--color-secondary-700)",
  "--color-fg-secondary-stronger": "var(--color-secondary-800)",
  "--color-fg-secondary-strongest": "var(--color-secondary-900)",
  "--border-radius-none": "var(--dimensions-0)",
  "--border-radius-xs": "var(--dimensions-2)",
  "--border-radius-s": "var(--dimensions-4)",
  "--border-radius-m": "var(--dimensions-8)",
  "--border-radius-l": "var(--dimensions-16)",
  "--border-radius-xl": "var(--dimensions-24)",
  "--border-width-none": "var(--dimensions-0)",
  "--border-width-s": "var(--dimensions-1)",
  "--border-width-m": "var(--dimensions-2)",
  "--border-width-l": "var(--dimensions-4)",
  "--height-xxxs": "var(--dimensions-12)",
  "--height-xxs": "var(--dimensions-16)",
  "--height-xs": "var(--dimensions-20)",
  "--height-s": "var(--dimensions-24)",
  "--height-m": "var(--dimensions-32)",
  "--height-l": "var(--dimensions-36)",
  "--height-xl": "var(--dimensions-40)",
  "--height-xxl": "var(--dimensions-48)",
  "--height-xxxl": "var(--dimensions-56)",
  "--shadow-100":
    "var(--dimensions-0) var(--dimensions-2) var(--dimensions-2) var(--dimensions-0) var(--color-alpha-400-a)",
  "--shadow-200":
    "var(--dimensions-0) var(--dimensions-12) var(--dimensions-12) var(--dimensions-0) var(--color-alpha-300-a)",
  "--shadow-300":
    "var(--dimensions-0) var(--dimensions-24) var(--dimensions-24) var(--dimensions-0) var(--color-alpha-300-a)",
  "--shadow-400":
    "var(--dimensions-0) var(--dimensions-48) var(--dimensions-48) var(--dimensions-0) var(--color-alpha-300-a)",
  "--spacing-gap-none": "var(--dimensions-0)",
  "--spacing-gap-xxs": "var(--dimensions-2)",
  "--spacing-gap-xs": "var(--dimensions-4)",
  "--spacing-gap-s": "var(--dimensions-8)",
  "--spacing-gap-m": "var(--dimensions-12)",
  "--spacing-gap-ml": "var(--dimensions-16)",
  "--spacing-gap-l": "var(--dimensions-24)",
  "--spacing-gap-xl": "var(--dimensions-32)",
  "--spacing-gap-xxl": "var(--dimensions-48)",
  "--spacing-padding-none": "var(--dimensions-0)",
  "--spacing-padding-xxxs": "var(--dimensions-2)",
  "--spacing-padding-xxs": "var(--dimensions-4)",
  "--spacing-padding-xs": "var(--dimensions-8)",
  "--spacing-padding-s": "var(--dimensions-12)",
  "--spacing-padding-m": "var(--dimensions-16)",
  "--spacing-padding-ml": "var(--dimensions-20)",
  "--spacing-padding-l": "var(--dimensions-24)",
  "--spacing-padding-xl": "var(--dimensions-32)",
  "--spacing-padding-xxl": "var(--dimensions-40)",
  "--typography-body-xs": "var(--font-size-12)",
  "--typography-body-s": "var(--font-size-14)",
  "--typography-body-m": "var(--font-size-16)",
  "--typography-body-l": "var(--font-size-18)",
  "--typography-body-xl": "var(--font-size-20)",
  "--typography-body-xxl": "var(--font-size-24)",
  "--typography-body-regular": "var(--font-weight-regular)",
  "--typography-heading-xs": "var(--font-size-12)",
  "--typography-heading-s": "var(--font-size-16)",
  "--typography-heading-m": "var(--font-size-20)",
  "--typography-heading-l": "var(--font-size-24)",
  "--typography-heading-xl": "var(--font-size-32)",
  "--typography-heading-xxl": "var(--font-size-40)",
  "--typography-heading-light": "var(--font-weight-light)",
  "--typography-heading-regular": "var(--font-weight-regular)",
  "--typography-heading-semibold": "var(--font-weight-semibold)",
  "--typography-helper-text-s": "var(--font-size-12)",
  "--typography-helper-text-m": "var(--font-size-14)",
  "--typography-helper-text-l": "var(--font-size-16)",
  "--typography-helper-text-light": "var(--font-weight-light)",
  "--typography-helper-text-regular": "var(--font-weight-regular)",
  "--typography-helper-text-semibold": "var(--font-weight-semibold)",
  "--typography-helper-text-italic": "var(--font-style-lightitalic)",
  "--typography-label-s": "var(--font-size-12)",
  "--typography-label-m": "var(--font-size-14)",
  "--typography-label-l": "var(--font-size-16)",
  "--typography-label-xl": "var(--font-size-20)",
  "--typography-label-regular": "var(--font-weight-regular)",
  "--typography-label-semibold": "var(--font-weight-semibold)",
  "--typography-link-m": "var(--font-size-14)",
  "--typography-link-regular": "var(--font-weight-regular)",
  "--typography-title-s": "var(--font-size-14)",
  "--typography-title-m": "var(--font-size-16)",
  "--typography-title-l": "var(--font-size-20)",
  "--typography-title-xl": "var(--font-size-24)",
  "--typography-title-bold": "var(--font-weight-bold)",
  "--border-style-default": "var(--line-style-solid)",
  "--border-style-outline": "var(--line-style-dashed)",
  "--typography-font-family": "var(--font-family-sans)",
};
