import React from "react";
import { DxcButton } from "@diaas/dxc-react-cdk";
import homeLogo from "../images/home.svg";

function App() {
  const onClick = () => {};

  return (
    <div>
      <div>
        <h3>Button Component</h3>
        <h4>Sizes</h4>
        <DxcButton
          mode="basic"
          theme="light"
          label="Small"
          onClick={onClick}
          size="small"
          margin="small"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="Medium"
          onClick={onClick}
          size="medium"
          margin="small"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="Large"
          onClick={onClick}
          size="large"
          margin="small"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="Fit Content"
          onClick={onClick}
          size="fitContent"
          margin="small"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="Fill Parent"
          onClick={onClick}
          size="fillParent"
          margin="small"
        />
      </div>
      <div>
        <h4>Margins</h4>
        <DxcButton
          mode="basic"
          theme="light"
          label="xxsmall"
          onClick={onClick}
          size="medium"
          margin="xxsmall"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="xsmall"
          onClick={onClick}
          size="medium"
          margin="xsmall"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="small"
          onClick={onClick}
          size="medium"
          margin="small"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="medium"
          onClick={onClick}
          size="medium"
          margin="medium"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="large"
          onClick={onClick}
          size="medium"
          margin="large"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="xlarge"
          onClick={onClick}
          size="medium"
          margin="xlarge"
        />
        <DxcButton
          mode="basic"
          theme="light"
          label="xxlarge"
          onClick={onClick}
          size="medium"
          margin="xxlarge"
        />
      </div>
      <h4>Basic Button</h4>
      <div style={{ display: "flex" }}>
        <div>
          <DxcButton
            mode="basic"
            label="Button"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="basic"
            theme="light"
            label="But"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="basic"
            theme="light"
            label="But"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="basic"
            theme="light"
            label="ButL"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="basic"
            theme="light"
            label="ButM"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
      </div>
      <h4>Raised Button</h4>
      <div style={{ display: "flex" }}>
        <div>
          <DxcButton
            mode="raised"
            label="Button"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="raised"
            theme="light"
            label="But"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="raised"
            theme="light"
            label="But"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="raised"
            theme="light"
            label="ButL"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="raised"
            theme="light"
            label="ButM"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
      </div>
      <h4>Flat Button</h4>
      <div style={{ display: "flex" }}>
        <div>
          <DxcButton
            mode="flat"
            label="Button"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="flat"
            theme="light"
            label="But"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="flat"
            theme="light"
            label="But"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="flat"
            theme="light"
            label="ButL"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="flat"
            theme="light"
            label="ButM"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
      </div>
      <h4>Outlined Button</h4>
      <div style={{display:"flex"}}>
        <div>
          <DxcButton
            mode="outlined"
            label="Button"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="outlined"
            theme="light"
            label="But"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="outlined"
            theme="light"
            label="But"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="outlined"
            theme="light"
            label="ButL"
            iconPosition="after"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
        <div>
          <DxcButton
            mode="outlined"
            theme="light"
            label="ButM"
            iconPosition="before"
            onClick={onClick}
            iconSrc={homeLogo}
            size="medium"
            margin="xsmall"
          />
        </div>
      </div>
      <h4>Dark Theme</h4>
      <div style={{display:"flex", "background":"black"}}>
        <div>
          <DxcButton
            mode="basic"
            label="Basic button"
            theme="dark"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
        <DxcButton
            mode="raised"
            label="Raised button"
            theme="dark"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
        <DxcButton
            mode="flat"
            label="Flat button"
            theme="dark"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
        <div>
        <DxcButton
            mode="outlined"
            label="Outlined button"
            theme="dark"
            onClick={onClick}
            margin="xsmall"
          />
        </div>
      </div>
    </div>
  );
}

export default App;
