import {
  AccordionPreview,
  AlertPreview,
  AvatarPreview,
  BadgePreview,
  BreadcrumbsPreview,
  ButtonPreview,
  CheckboxPreview,
  ChipPreview,
  ContextualMenuPreview,
  DataGridPreview,
  DateInputPreview,
  DividerPreview,
  DropdownPreview,
  FileInputPreview,
  LinkPreview,
  NavTabsPreview,
  NumberInputPreview,
  PaginatorPreview,
  PasswordInputPreview,
  ProgressBarPreview,
  QuickNavPreview,
  RadioGroupPreview,
  ResultsetTablePreview,
  SelectPreview,
  SliderPreview,
  SpinnerPreview,
  StatusLightPreview,
  SwitchPreview,
  TablePreview,
  TabsPreview,
  TextareaPreview,
  TextInputPreview,
  ToastPreview,
  ToggleGroupPreview,
  TooltipPreview,
  WizardPreview,
} from "./previews/components";
import { ApplicationPreview, DashboardPreview, FormPreview } from "./previews/examples";

export const componentsRegistry = {
  "/components/accordion": AccordionPreview,
  "/components/avatar": AvatarPreview,
  "/components/divider": DividerPreview,
  "/components/wizard": WizardPreview,
  "/components/data-grid": DataGridPreview,
  "/components/paginator": PaginatorPreview,
  "/components/resultset-table": ResultsetTablePreview,
  "/components/table": TablePreview,
  "/components/alert": AlertPreview,
  "/components/progress-bar": ProgressBarPreview,
  "/components/spinner": SpinnerPreview,
  "/components/toast": ToastPreview,
  "/components/tooltip": TooltipPreview,
  "/components/button": ButtonPreview,
  "/components/checkbox": CheckboxPreview,
  "/components/date-input": DateInputPreview,
  "/components/file-input": FileInputPreview,
  "/components/number-input": NumberInputPreview,
  "/components/password-input": PasswordInputPreview,
  "/components/radio-group": RadioGroupPreview,
  "/components/select": SelectPreview,
  "/components/slider": SliderPreview,
  "/components/switch": SwitchPreview,
  "/components/text-input": TextInputPreview,
  "/components/textarea": TextareaPreview,
  "/components/toggle-group": ToggleGroupPreview,
  "/components/breadcrumbs": BreadcrumbsPreview,
  "/components/contextual-menu": ContextualMenuPreview,
  "/components/dropdown": DropdownPreview,
  "/components/link": LinkPreview,
  "/components/nav-tabs": NavTabsPreview,
  "/components/quick-nav": QuickNavPreview,
  "/components/tabs": TabsPreview,
  "/components/badge": BadgePreview,
  "/components/chip": ChipPreview,
  "/components/status-light": StatusLightPreview,
};

export const examplesRegistry = {
  "/examples/application": ApplicationPreview,
  "/examples/dashboard": DashboardPreview,
  "/examples/form": FormPreview,
};
