import {
  AccordionPreview,
  AlertPreview,
  AvatarPreview,
  BadgePreview,
  BreadcrumbsPreview,
  BulletedListPreview,
  ButtonPreview,
  CardPreview,
  CheckboxPreview,
  ChipPreview,
  ContextualMenuPreview,
  DataGridPreview,
  DateInputPreview,
  DialogPreview,
  DividerPreview,
  DropdownPreview,
  FileInputPreview,
  HeadingPreview,
  ImagePreview,
  LinkPreview,
  NavTabsPreview,
  NumberInputPreview,
  PaginatorPreview,
  ParagraphPreview,
  PasswordInputPreview,
  ProgressBarPreview,
  QuickNavPreview,
  RadioGroupPreview,
  ResultsetTablePreview,
  SelectPreview,
  SliderPreview,
  SpinnerPreview,
  StatusLightPreview,
  SwitchPreview,
  TablePreview,
  TabsPreview,
  TextareaPreview,
  TextInputPreview,
  ToastPreview,
  ToggleGroupPreview,
  TooltipPreview,
  TypographyPreview,
  WizardPreview,
} from "./previews";

export const componentsRegistry = {
  "/components/accordion": AccordionPreview,
  "/components/avatar": AvatarPreview,
  "/components/card": CardPreview,
  "/components/dialog": DialogPreview,
  "/components/divider": DividerPreview,
  "/components/image": ImagePreview,
  "/components/wizard": WizardPreview,
  "/components/data-grid": DataGridPreview,
  "/components/paginator": PaginatorPreview,
  "/components/resultset-table": ResultsetTablePreview,
  "/components/table": TablePreview,
  "/components/alert": AlertPreview,
  "/components/progress-bar": ProgressBarPreview,
  "/components/spinner": SpinnerPreview,
  "/components/toast": ToastPreview,
  "/components/tooltip": TooltipPreview,
  "/components/button": ButtonPreview,
  "/components/checkbox": CheckboxPreview,
  "/components/date-input": DateInputPreview,
  "/components/file-input": FileInputPreview,
  "/components/number-input": NumberInputPreview,
  "/components/password-input": PasswordInputPreview,
  "/components/radio-group": RadioGroupPreview,
  "/components/select": SelectPreview,
  "/components/slider": SliderPreview,
  "/components/switch": SwitchPreview,
  "/components/text-input": TextInputPreview,
  "/components/textarea": TextareaPreview,
  "/components/toggle-group": ToggleGroupPreview,
  // TODO: This should go into examples
  // "/components/application-layout": ApplicationLayoutPreview,
  // "/components/footer": FooterPreview,
  // "/components/header": HeaderPreview,
  // "/components/sidenav": SidenavPreview,
  // TODO: Should we keep layout components out?
  // "/components/bleed": BleedPreview,
  // "/components/container": ContainerPreview,
  // "/components/flex": FlexPreview,
  // "/components/grid": GridPreview,
  // "/components/inset": InsetPreview,
  // "/components/popover": PopoverPreview,
  "/components/breadcrumbs": BreadcrumbsPreview,
  "/components/contextual-menu": ContextualMenuPreview,
  "/components/dropdown": DropdownPreview,
  "/components/link": LinkPreview,
  "/components/nav-tabs": NavTabsPreview,
  "/components/quick-nav": QuickNavPreview,
  "/components/tabs": TabsPreview,
  "/components/badge": BadgePreview,
  "/components/chip": ChipPreview,
  "/components/status-light": StatusLightPreview,
  "/components/bulleted-list": BulletedListPreview,
  "/components/heading": HeadingPreview,
  "/components/paragraph": ParagraphPreview,
  "/components/typography": TypographyPreview,
};
