import { DxcFlex, DxcLink, DxcTable } from "@dxc-technology/halstack-react";
import QuickNavContainer from "@/common/QuickNavContainer";
import DocFooter from "@/common/DocFooter";
import Example from "@/common/example/Example";
import Code, { ExtendedTableCode, TableCode } from "@/common/Code";
import StatusBadge from "@/common/StatusBadge";
import Link from "next/link";
import dismissible from "./examples/dismissible";
import selectable from "./examples/selectable";

const prefixTypeString = `| string 
| SVG
| AvatarProps`;

const avatarPropsString = `{
  color: 'primary' | 'secondary' | 'tertiary'
    | 'success' | 'info' | 'neutral' | 'warning'
    | 'error';
  icon?: string | SVG;
  imgSrc?: string;
  profileName?: string;
};`;

const sections = [
  {
    title: "Props",
    content: (
      <DxcTable>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
            <th>Default</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>disabled</td>
            <td>
              <TableCode>boolean</TableCode>
            </td>
            <td>
              If true, the component will be disabled. When mode is <Code>"dismissible"</Code>, the chip cannot be
              disabled.
            </td>
            <td>
              <TableCode>false</TableCode>
            </td>
          </tr>
          <tr>
            <td>label</td>
            <td>
              <TableCode>string</TableCode>
            </td>
            <td>
              Text to be placed on the chip. When using an avatar as prefix or when mode is <Code>"dismissible"</Code>,
              the label is required to ensure proper accessibility.
            </td>
            <td>-</td>
          </tr>
          <tr>
            <td>
              <DxcFlex direction="column" gap="var(--spacing-gap-xs)" alignItems="baseline">
                <StatusBadge status="new" />
                mode
              </DxcFlex>
            </td>
            <td>
              <TableCode>"selectable" | "dismissible"</TableCode>
            </td>
            <td>
              Determines the visual style and functionality of the chip. Available modes are:
              <ul>
                <li>
                  <strong>selectable</strong>: The whole chip is an interactive element that allows users to activate or
                  clear options directly within the interface.
                </li>
                <li>
                  <strong>dismissible</strong>: Dismissible chip is used to represent information generated by user
                  input within an interface.
                </li>
              </ul>
            </td>
            <td>
              <TableCode>"selectable"</TableCode>
            </td>
          </tr>
          <tr>
            <td>
              <DxcFlex direction="column" gap="var(--spacing-gap-xs)" alignItems="baseline">
                <StatusBadge status="new" />
                onClick
              </DxcFlex>
            </td>
            <td>
              <TableCode>{"() => void"}</TableCode>
            </td>
            <td>Function to be called when the chip is clicked or the dismiss action is triggered.</td>
            <td>-</td>
          </tr>
          <tr>
            <td>
              <DxcFlex direction="column" gap="var(--spacing-gap-xs)" alignItems="baseline">
                <StatusBadge status="new" />
                prefix
              </DxcFlex>
            </td>
            <td>
              <ExtendedTableCode>{prefixTypeString}</ExtendedTableCode>
              <p>
                being <Code>AvatarProps</Code> an object with the following properties:
              </p>
              <ExtendedTableCode>{avatarPropsString}</ExtendedTableCode>
            </td>
            <td>
              <DxcLink newWindow href="https://fonts.google.com/icons">
                Material Symbol
              </DxcLink>{" "}
              name or SVG element used as the icon. When using Material Symbols, replace spaces with underscores. By
              default, symbols are outlined; to use the filled version, prefix the symbol name with{" "}
              <TableCode>"filled_"</TableCode>. If a string or SVG is provided, it will be rendered as an icon placed
              before the chip label. If an avatar props object is provided, a{" "}
              <Link href="/components/avatar" passHref legacyBehavior>
                <DxcLink>DxcAvatar</DxcLink>
              </Link>{" "}
              will be displayed to the left of the label.
            </td>
            <td>-</td>
          </tr>
          <tr>
            <td>
              <DxcFlex direction="column" gap="var(--spacing-gap-xs)" alignItems="baseline">
                <StatusBadge status="new" />
                selected
              </DxcFlex>
            </td>
            <td>
              <TableCode>boolean</TableCode>
            </td>
            <td>
              If true, the component will be selected. If undefined, the component manages its own internal state
              (uncontrolled mode). This property is only applicable when the mode is <Code>"selectable"</Code>.
            </td>
            <td>-</td>
          </tr>
          <tr>
            <td>tabIndex</td>
            <td>
              <TableCode>number</TableCode>
            </td>
            <td>
              Value of the <Code>tabindex</Code> attribute applied to the component when mode is{" "}
              <Code>"selectable"</Code> and clear icon when mode is <Code>"dismissible"</Code>.
            </td>
            <td>
              <TableCode>0</TableCode>
            </td>
          </tr>
        </tbody>
      </DxcTable>
    ),
  },
  {
    title: "Examples",
    subSections: [
      {
        title: "Selectable",
        content: <Example example={selectable} defaultIsVisible />,
      },
      {
        title: "Dismissible",
        content: (
          <>
            <Example example={dismissible} defaultIsVisible />
          </>
        ),
      },
    ],
  },
];

const ChipCodePage = () => {
  return (
    <DxcFlex direction="column" gap="4rem">
      <QuickNavContainer sections={sections} startHeadingLevel={2} />
      <DocFooter githubLink="https://github.com/dxc-technology/halstack-react/blob/master/apps/website/screens/components/chip/code/ChipCodePage.tsx" />
    </DxcFlex>
  );
};

export default ChipCodePage;
