export const componentCategories = {
  Core: [
    { id: "accordion", name: "Accordion" },
    { id: "alert", name: "Alert" },
    { id: "avatar", name: "Avatar" },
    { id: "basicAppLayout", name: "AppLayout" },
    { id: "badge", name: "Badge" },
    { id: "breadcrumb", name: "Breadcrumb" },
    { id: "button", name: "Button" },
    { id: "checkbox", name: "Checkbox" },
    { id: "chip", name: "Chip" },
    { id: "contextual", name: "Contextual" },
    { id: "dataGrid", name: "DataGrid" },
    { id: "date", name: "Date input" },
    { id: "divider", name: "Divider" },
    { id: "dropdown", name: "Dropdown" },
    { id: "fileInput", name: "FileInput" },
    { id: "link", name: "Link" },
    { id: "number", name: "Number" },
    { id: "paginator", name: "Paginator" },
    { id: "password", name: "Password" },
    { id: "popover", name: "Popover" },
    { id: "progressBar", name: "ProgressBar" },
    { id: "quickNav", name: "QuickNav" },
    { id: "radio", name: "Radio" },
    { id: "select", name: "Select" },
    { id: "slider", name: "Slider" },
    { id: "spinner", name: "Spinner" },
    { id: "statusLight", name: "StatusLight" },
    { id: "switch", name: "Switch" },
    { id: "table", name: "Table" },
    { id: "tabs", name: "Tabs" },

    { id: "textInput", name: "Text input" },
    { id: "textarea", name: "Textarea" },
    { id: "toast", name: "Toast" },
    { id: "toggle", name: "Toggle" },
    { id: "wizard", name: "Wizard" },
  ],
  Other: [
    { id: "fullAppLayout", name: "AppExample" },
    { id: "simpleForm", name: "Form" },
    { id: "login", name: "Login" },
    { id: "dashboard", name: "Dashboard" },
  ],
};
