import headerLogo from "../header/dxc_logo_blk_rgb.svg";
import headerLogoResponsive from "../header/dxc_logo_blk_rgb.svg";
import footerLogo from "../footer/dxc_logo_wht.png";

export const globalTokens = {
  black: "#000000",
  lightBlack: "#212121",
  yellow: "#FFED00",
  lightGrey: "#D9D9D9",
  darkRed: "#D0011B",
  lightRed: "#FF6161",
  lightBlue: "#CEE0F5",
  lightYellow: "#FCF2BD",
  lightPink: "#F9CFCF",
  lightGreen: "#DBF1C4",
  blue: "#005FCC",
  lighterGrey: "#F8F8F8",
  red: "#D0011B",
  violet: "#8800F6",
  darkBlue: "#006BF6",
  inherit: "inherit",
  transparent: "transparent",
  purple: "#6f2c91",
  mediumPurple: "#ead8f3",
  lightPurple: "#f5ebf9",
  lighterPurple: "#d0bddb",
  white: "#ffffff",
  darkGrey: "#666666",
  mediumGrey: "#bfbfbf",
  mediumWhite: "#f9f9f9",
  mediumBlue: "#0067b3",
  softBlue: "#b1cee6",
  darkWhite: "#eeeeee",
  lighterBlack: "#b1b1b1",
  mediumBlack: "#676767",
  mediumGreyBlack: "#dbdbdb",
  lightWhite: "#f2f2f2",
  softGrey: "#cecece",
  softBlack: "#565656",
};
export const defaultTheme = {
  date: {
    pickerSelectedDateBackgroundColor: "#6f2c91",
    pickerSelectedDateColor: "#ffffff",
  },
  inputText: {
    selectedOptionBackgroundColor: "#D9D9D9",
  },
  
  wizard: {
    selectedBackgroundColor: "#6f2c91",
    selectedFont: "#ffffff",
  },
};
export const componentTokens = {
  accordion: {
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.darkGrey,
    arrowColor: globalTokens.purple,
    hoverBackgroundColor: globalTokens.lightPurple,
    disabledFontColor: globalTokens.mediumGrey,
    focusOutline: globalTokens.purple,
  },
  alert: {
    overlayColor: globalTokens.black,
    infoColor: globalTokens.lightBlue,
    confirmColor: globalTokens.lightGreen,
    warningColor: globalTokens.lightYellow,
    errorColor: globalTokens.lightPink,
    focusColor: globalTokens.blue,
  },
  button: {
    primaryBackgroundColor: globalTokens.purple,
    primaryHoverBackgroundColor: globalTokens.black,
    primaryFontColor: globalTokens.white,
    primaryHoverFontColor: globalTokens.white,
    primaryActiveBackgroundColor: globalTokens.mediumBlack,
    disabledPrimaryBackgroundColor: globalTokens.lighterPurple,
    disabledPrimaryFontColor: globalTokens.white,
    secondaryOutlinedColor: globalTokens.purple,
    secondaryBackgroundColor: globalTokens.transparent,
    hoverOutlinedColor: globalTokens.black,
    secondaryFontColor: globalTokens.black,
    secondaryHoverFontColor: globalTokens.black,
    secondaryActiveBackgroundColor: globalTokens.mediumGreyBlack,
    secondaryHoverBackgroundColor: globalTokens.darkWhite,
    disabledSecondaryOutlinedColor: globalTokens.lighterPurple,
    disabledSecondaryFontColor: globalTokens.lighterBlack,
    textBackgroundColor: globalTokens.transparent,
    textHoverBackgroundColor: globalTokens.black,
    textFontColor: globalTokens.purple,
    textHoverFontColor: globalTokens.white,
    textActiveBackgroundColor: globalTokens.mediumBlack,
    disabledTextFontColor: globalTokens.lighterPurple,
    focusColor: globalTokens.blue,
  },
  box: {
    backgroundColor: globalTokens.white,
  },
  card: {
    backgroundColor: globalTokens.white,
  },
  checkbox: {
    backgroundColorChecked: globalTokens.mediumBlue,
    borderColor: globalTokens.mediumBlue,
    checkColor: globalTokens.white,
    fontColor: globalTokens.inherit,
    disabledBackgroundColorChecked: globalTokens.softBlue,
    disabledBorderColor: globalTokens.softBlue,
    disabledCheckColor: globalTokens.white,
    disabledFontColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
  },
  chip: {
    backgroundColor: globalTokens.darkWhite,
    outlinedColor: "",
    fontColor: globalTokens.black,
    disabledBackgroundColor: globalTokens.mediumWhite,
    disabledFontColor: globalTokens.lighterBlack,
  },
  date: {
    pickerSelectedDateBackgroundColor: globalTokens.purple,
    pickerSelectedDateColor: globalTokens.white,
    pickerBackgroundColor: globalTokens.white,
    pickerFontColor: globalTokens.black,
    pickerActualDate: globalTokens.lightGrey,
    pickerHoverDateBackgroundColor: globalTokens.lighterPurple,
    pickerHoverDateFontColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    focusColor: globalTokens.blue,
  },
  dialog: {
    overlayColor: globalTokens.black,
    separator: globalTokens.lightGrey,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    backgroundColor: globalTokens.white,
  },
  dropdown: {
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.black,
    dropdownBackgroundColor: globalTokens.white,
    dropdownFontColor: globalTokens.black,
    hoverBackgroundOption: globalTokens.white,
    hoverBackgroundColor: globalTokens.white,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    focusColor: globalTokens.blue,
  },
  footer: {
    backgroundColor: globalTokens.black,
    fontColor: globalTokens.white,
    lineColor: globalTokens.mediumBlue,
    logo: footerLogo,
  },
  header: {
    backgroundColor: globalTokens.white,
    underlinedColor: globalTokens.black,
    fontColor: globalTokens.black,
    backgroundColorMenu: globalTokens.white,
    fontColorMenu: globalTokens.black,
    hamburguerColor: globalTokens.black,
    hoverHamburguerColor: globalTokens.mediumGreyBlack,
    overlayColor: globalTokens.softBlack,
    focusColor: globalTokens.blue,
    logo: headerLogo,
    logoResponsive: headerLogoResponsive,
  },
  inputText: {
    fontColor: globalTokens.black,
    disabledFontColor: globalTokens.lighterBlack,
    placeholderColor: globalTokens.lightGrey,
    error: globalTokens.red,
    selectedOptionBackgroundColor: globalTokens.lightWhite,
    hoverOptionColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
  },
  link: {
    fontColor: globalTokens.blue,
    visitedFontColor: globalTokens.violet,
    underlinedBackgroundColor: globalTokens.blue,
    visitedUnderlinedBackgroundColor: globalTokens.violet,
    disabledColor: globalTokens.lightGrey,
    disabledUnderlinedBackgroundColor: globalTokens.lightGrey,
    hoverFontColor: globalTokens.darkBlue,
  },
  paginator: {
    paginatorBackgroundColor: globalTokens.darkWhite,
    paginatorFontColor: globalTokens.black,
  },
  progressBar: {
    trackLine: globalTokens.yellow,
    totalLine: globalTokens.black,
    fontColor: globalTokens.inherit,
    opaqueTotalLine:globalTokens.lighterBlack,
    overlayColor: globalTokens.black,
  },
  radio: {
    color: globalTokens.black,
    disabledColor: globalTokens.lighterBlack,
    fontColor: globalTokens.inherit,
    disabledFontColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
  },
  select: {
    selectedOptionBackgroundColor: globalTokens.lightGrey,
    color: globalTokens.black,
    hoveredOptionBackgroundColor: globalTokens.lightWhite,
    error: globalTokens.red,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    disabledColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
  },
  sidenav: {
    backgroundColor: globalTokens.lighterGrey,
    arrowContainerColor: globalTokens.lightGrey,
    arrowColor: globalTokens.black,
  },
  slider: {
    color: globalTokens.mediumBlue,
    totalLine: globalTokens.softBlue,
    disabledthumbBackgroundColor: globalTokens.softBlue,
    disableddotsBackgroundColor: globalTokens.softBlue,
    focusColor: globalTokens.blue,
  },
  spinner: {
    trackCircleColor: globalTokens.yellow,
    totalCircleColor: globalTokens.white,
    fontColor: globalTokens.inherit,
    overlayColor: globalTokens.black,
  },
  switch: {
    checkedTrackBackgroundColor: globalTokens.darkGrey,
    disabledCheckedTrackBackgroundColor: globalTokens.softGrey,
    checkedThumbBackgroundColor: globalTokens.white,
    uncheckedThumbBackgroundColor: globalTokens.white,
    uncheckedTrackBackgroundColor: globalTokens.lightGrey,
    disabledUncheckedTrackBackgroundColor: globalTokens.lightWhite,
    fontColor: globalTokens.black,
    disabledFontColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
  },
  table: {
    headerBackgroundColor: globalTokens.purple,
    headerFontColor: globalTokens.white,
    separatorColor: globalTokens.lightGrey,
    bodyBackgroundColor: globalTokens.white,
    bodyFontColor: globalTokens.black,
  },
  tabs: {
    selectedFontColor: globalTokens.purple,
    selectedIconColor: globalTokens.purple,
    selectedUnderlineColor: globalTokens.purple,
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.darkGrey,
    disabledFontColor: globalTokens.mediumGrey,
    focusOutline: globalTokens.purple,
    divider: globalTokens.mediumGrey,
    hoverBackgroundColor: globalTokens.lightPurple,
    pressedBackgroundColor: globalTokens.mediumPurple,
  },
  tag: {
    backgroundColor: globalTokens.white,
  },
  toggleGroup: {
    selectedBackgroundColor: globalTokens.purple,
    disabledSelectedBackgroundColor: globalTokens.lighterPurple,
    selectedBackgroundHoverColor: globalTokens.black,
    selectedFontColor: globalTokens.white,
    selectedHoverFontColor: globalTokens.white,
    unselectedBackgroundColor: globalTokens.lightGrey,
    disabledUnselectedBackgroundColor: globalTokens.lighterPurple,
    unselectedBackgroundHoverColor: globalTokens.darkWhite,
    unselectedFontColor: globalTokens.black,
    unselectedHoverFontColor: globalTokens.black,
  },
  textarea: {
    fontColor: globalTokens.black,
    placeholderColor: globalTokens.lightGrey,
    disabled: 0.34,
    error: globalTokens.red,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
  },
  wizard: {
    selectedBackgroundColor: globalTokens.yellow,
    selectedFont: globalTokens.black,
    borderColor: globalTokens.black,
    fontColor: globalTokens.inherit,
    lineColor: globalTokens.lightGrey,
    disabledBackground: globalTokens.lightGrey,
    disabledFont: globalTokens.darkGrey,
    disabled: 0.34,
    notVisitedOpacity: 0.64,
  },
};
export const spaces = {
  xxsmall: "6px",
  xsmall: "16px",
  small: "24px",
  medium: "36px",
  large: "48px",
  xlarge: "64px",
  xxlarge: "100px",
};
export const responsiveSizes = {
  mobileSmall: "320",
  mobileMedium: "375",
  mobileLarge: "425",
  tablet: "768",
  laptop: "1024",
  desktop: "1440",
};
export const typeface = {
  body: {
    fontSize: "16px",
    letterSpacing: "0.5",
    textTransform: "initial",
  },
  altBody: {
    fontSize: "14px",
    letterSpacing: "0.25",
    textTransform: "initial",
  },
  subtitle: {
    fontSize: "16px",
    letterSpacing: "0.15",
    textTransform: "initial",
  },
  altSubtitle: {
    fontSize: "14px",
    letterSpacing: "0.1",
    textTransform: "initial",
  },
  caption: {
    fontSize: "12px",
    letterSpacing: "0.4",
    textTransform: "initial",
  },
  overline: {
    fontSize: "12px",
    letterSpacing: "2",
    textTransform: "uppercase",
  },
};
