import headerLogo from "../header/dxc_logo_blk_rgb.svg";
import headerLogoResponsive from "../header/dxc_logo_blk_rgb.svg";
import footerLogo from "../footer/dxc_logo_wht.png";

export const globalTokens = {
  black: "#000000",
  lightBlack: "#212121",
  yellow: "#FFED00",
  lightGrey: "#D9D9D9",
  darkRed: "#D0011B",
  lightRed: "#FF6161",
  lightBlue: "#CEE0F5",
  lightYellow: "#FCF2BD",
  lightPink: "#F9CFCF",
  lightGreen: "#DBF1C4",
  blue: "#005FCC",
  lighterGrey: "#F8F8F8",
  red: "#D0011B",
  violet: "#8800F6",
  darkBlue: "#006BF6",
  inherit: "inherit",
  transparent: "transparent",
  purple: "#6f2c91",
  mediumPurple: "#ead8f3",
  lightPurple: "#f5ebf9",
  lighterPurple: "#d0bddb",
  white: "#ffffff",
  darkGrey: "#666666",
  mediumGrey: "#bfbfbf",
  mediumWhite: "#f9f9f9",
  mediumBlue: "#0067b3",
  softBlue: "#b1cee6",
  darkWhite: "#eeeeee",
  lighterBlack: "#b1b1b1",
  mediumBlack: "#676767",
  mediumGreyBlack: "#dbdbdb",
  lightWhite: "#f2f2f2",
  softGrey: "#cecece",
  softBlack: "#565656",
  fontSize10: "10px",
  type_sans: "Open Sans, sans-serif",
  type_scale_root: "16px",
  type_scale_08: "3.75rem",
  type_scale_07: "3rem",
  type_scale_06: "2rem",
  type_scale_05: "1.5rem",
  type_scale_04: "1.25rem",
  type_scale_03: "1rem",
  type_scale_02: "0.875rem",
  type_scale_01: "0.75rem",
  type_ligth: "300",
  type_regular: "400",
  type_semibold: "600",
  type_bold: "bold",
  type_italic: "italic",
  type_normal: "normal",
  type_spacing_tight_02: "-0.05em",
  type_spacing_tight_01: "-0.025em",
  type_spacing_normal: "0",
  type_spacing_wide_01: "0.025em",
  type_spacing_wide_02: "0.05em",
  type_spacing_wide_03: "0.1em",
  type_initial: "initial",
  type_uppercase: "uppercase",
  type_no_line: "none",
  type_underline: "underline",
  type_line_through: "line-through",
  type_leading_compact_03: "1em",
  type_leading_compact_02: "1.25em",
  type_leading_compact_01: "1.365em",
  type_leading_normal: "1.5em",
  type_leading_loose_01: "1.75em",
  type_leading_loose_02: "2em",
};

export const componentTokens = {
  accordion: {
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.darkGrey,
    arrowColor: globalTokens.purple,
    hoverBackgroundColor: globalTokens.lightPurple,
    disabledFontColor: globalTokens.mediumGrey,
    focusOutline: globalTokens.purple,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
    fontWeight: globalTokens.type_ligth,
    fontStyle: globalTokens.type_italic,
    fontLetterSpacingWide01: globalTokens.type_spacing_wide_01,
  },
  alert: {
    overlayColor: globalTokens.black,
    infoColor: globalTokens.lightBlue,
    confirmColor: globalTokens.lightGreen,
    warningColor: globalTokens.lightYellow,
    errorColor: globalTokens.lightPink,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_01,
    fontTextTransform: globalTokens.type_uppercase,
    fontWeight: globalTokens.type_bold,
  },
  button: {
    primaryBackgroundColor: globalTokens.purple,
    primaryHoverBackgroundColor: globalTokens.black,
    primaryFontColor: globalTokens.white,
    primaryHoverFontColor: globalTokens.white,
    primaryActiveBackgroundColor: globalTokens.mediumBlack,
    disabledPrimaryBackgroundColor: globalTokens.lighterPurple,
    disabledPrimaryFontColor: globalTokens.white,
    secondaryOutlinedColor: globalTokens.purple,
    secondaryBackgroundColor: globalTokens.transparent,
    hoverOutlinedColor: globalTokens.black,
    secondaryFontColor: globalTokens.black,
    secondaryHoverFontColor: globalTokens.black,
    secondaryActiveBackgroundColor: globalTokens.mediumGreyBlack,
    secondaryHoverBackgroundColor: globalTokens.darkWhite,
    disabledSecondaryOutlinedColor: globalTokens.lighterPurple,
    disabledSecondaryFontColor: globalTokens.lighterBlack,
    textBackgroundColor: globalTokens.transparent,
    textHoverBackgroundColor: globalTokens.black,
    textFontColor: globalTokens.purple,
    textHoverFontColor: globalTokens.white,
    textActiveBackgroundColor: globalTokens.mediumBlack,
    disabledTextFontColor: globalTokens.lighterPurple,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_02,
    fontLineHeight: globalTokens.type_leading_normal,
    fontWeight: globalTokens.type_regular,
    fontLetterSpacingWide01: globalTokens.type_spacing_wide_01,
  },
  box: {
    backgroundColor: globalTokens.white,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_02,
    fontLetterSpacingWide01: globalTokens.type_spacing_wide_01,
  },
  card: {
    backgroundColor: globalTokens.white,
    textDecoration: globalTokens.type_no_line,
  },
  checkbox: {
    backgroundColorChecked: globalTokens.mediumBlue,
    borderColor: globalTokens.mediumBlue,
    checkColor: globalTokens.white,
    fontColor: globalTokens.inherit,
    disabledBackgroundColorChecked: globalTokens.softBlue,
    disabledBorderColor: globalTokens.softBlue,
    disabledCheckColor: globalTokens.white,
    disabledFontColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
  },
  chip: {
    backgroundColor: globalTokens.darkWhite,
    outlinedColor: "",
    fontColor: globalTokens.black,
    disabledBackgroundColor: globalTokens.mediumWhite,
    disabledFontColor: globalTokens.lighterBlack,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  date: {
    pickerSelectedDateBackgroundColor: globalTokens.purple,
    pickerSelectedDateColor: globalTokens.white,
    pickerBackgroundColor: globalTokens.white,
    pickerFontColor: globalTokens.black,
    pickerActualDate: globalTokens.lightGrey,
    pickerHoverDateBackgroundColor: globalTokens.lighterPurple,
    pickerHoverDateFontColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_06,
  },
  dialog: {
    overlayColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    backgroundColor: globalTokens.white,
    fontFamily: globalTokens.type_sans,
  },
  dropdown: {
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.black,
    dropdownBackgroundColor: globalTokens.white,
    dropdownFontColor: globalTokens.black,
    hoverBackgroundOption: globalTokens.white,
    hoverBackgroundColor: globalTokens.white,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  footer: {
    backgroundColor: globalTokens.black,
    fontColor: globalTokens.white,
    lineColor: globalTokens.mediumBlue,
    logo: footerLogo,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_01,
    textDecoration: globalTokens.type_no_line,
  },
  header: {
    backgroundColor: globalTokens.white,
    underlinedColor: globalTokens.black,
    fontColor: globalTokens.black,
    backgroundColorMenu: globalTokens.white,
    fontColorMenu: globalTokens.black,
    hamburguerColor: globalTokens.black,
    hoverHamburguerColor: globalTokens.mediumGreyBlack,
    overlayColor: globalTokens.softBlack,
    focusColor: globalTokens.blue,
    logo: headerLogo,
    logoResponsive: headerLogoResponsive,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.fontSize10,
    fontWeight: globalTokens.type_semibold,
    fontTextTransform: globalTokens.type_uppercase,
  },
  heading: {
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize16: globalTokens.type_scale_03,
    fontSize20: globalTokens.type_scale_04,
    fontSize24: globalTokens.type_scale_05,
    fontSize34: globalTokens.type_scale_06,
    fontSize48: globalTokens.type_scale_07,
    fontSize60: globalTokens.type_scale_08,
    fontWeightLight: globalTokens.type_light,
    fontWeight400: globalTokens.type_regular,
    fontWeight600: globalTokens.type_semibold,
    fontHeightLevelCompact: globalTokens.type_leading_compact_01,
    fontHeightLevelNormal: globalTokens.type_leading_normal,
    fontLetterSpacingTight01: globalTokens.type_spacing_tight_01,
    fontLetterSpacingNormal: globalTokens.type_spacing_normal,
    fontLetterSpacingWide01: globalTokens.type_spacing_wide_01,
  },
  inputText: {
    fontColor: globalTokens.black,
    disabledFontColor: globalTokens.lighterBlack,
    placeholderColor: globalTokens.lightGrey,
    error: globalTokens.red,
    selectedOptionBackgroundColor: globalTokens.lightWhite,
    hoverOptionColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  link: {
    fontColor: globalTokens.blue,
    visitedFontColor: globalTokens.violet,
    underlinedBackgroundColor: globalTokens.blue,
    visitedUnderlinedBackgroundColor: globalTokens.violet,
    disabledColor: globalTokens.lightGrey,
    disabledUnderlinedBackgroundColor: globalTokens.lightGrey,
    hoverFontColor: globalTokens.darkBlue,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
    textDecoration: globalTokens.type_no_line,
  },
  paginator: {
    paginatorBackgroundColor: globalTokens.darkWhite,
    paginatorFontColor: globalTokens.black,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_02,
  },
  progressBar: {
    trackLine: globalTokens.purple,
    totalLine: globalTokens.softGrey,
    fontColor: globalTokens.inherit,
    overlayColor: globalTokens.black,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_01,
    fontTextTransform: globalTokens.type_uppercase,
  },
  radio: {
    color: globalTokens.black,
    disabledColor: globalTokens.lighterBlack,
    fontColor: globalTokens.inherit,
    disabledFontColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
  },
  select: {
    selectedOptionBackgroundColor: globalTokens.lightGrey,
    color: globalTokens.black,
    hoveredOptionBackgroundColor: globalTokens.lightWhite,
    error: globalTokens.red,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    disabledColor: globalTokens.lighterBlack,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  sidenav: {
    backgroundColor: globalTokens.lighterGrey,
    arrowContainerColor: globalTokens.lightGrey,
    arrowColor: globalTokens.black,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize24: globalTokens.type_scale_05,
    fontSize12: globalTokens.type_scale_01,
    fontSize14: globalTokens.type_scale_02,
    fontTextTransform: globalTokens.type_uppercase,
    fontStyle: globalTokens.type_normal,
    fontLetterSpacingTitle: globalTokens.type_spacing_normal,
    fontLetterSpacingSubtitle: globalTokens.type_spacing_wide_03,
    fontLetterSpacingLink: globalTokens.type_spacing_wide_01,
    textDecoration: globalTokens.type_no_line,
  },
  slider: {
    thumbBackgroundColor: globalTokens.mediumBlue,
    dotsBackgroundColor: globalTokens.mediumBlue,
    trackLine: globalTokens.mediumBlue,
    totalLine: globalTokens.softBlue,
    disabledThumbBackgroundColor: globalTokens.softBlue,
    disabledDotsBackgroundColor: globalTokens.softBlue,
    disabledTrackLine: globalTokens.softBlue,
    focusColor: globalTokens.blue,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  spinner: {
    trackCircleColor: globalTokens.purple,
    totalCircleColor: globalTokens.white,
    fontColor: globalTokens.inherit,
    overlayColor: globalTokens.black,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_01,
    fontTextTransform: globalTokens.type_uppercase,
  },
  switch: {
    checkedTrackBackgroundColor: globalTokens.purple,
    checkedThumbBackgroundColor: globalTokens.white,
    uncheckedTrackBackgroundColor: globalTokens.lightGrey,
    uncheckedThumbBackgroundColor: globalTokens.white,
    disabledCheckedTrackBackgroundColor: globalTokens.purple,
    disabledCheckedThumbBackgroundColor: globalTokens.white,
    disabledUncheckedTrackBackgroundColor: globalTokens.lightGrey,
    disabledUncheckedThumbBackgroundColor: globalTokens.white,
    disabledLabelFontColor: globalTokens.black,
    disabledLabelFontStyle: globalTokens.type_normal,
    labelFontFamily: globalTokens.type_sans,
    labelFontSize: globalTokens.type_scale_root,
    labelFontStyle: globalTokens.type_normal,
    labelFontWeight: globalTokens.type_regular,
    labelFontColor: globalTokens.black,
    labelMarginRight: "0px",
    thumbFocusColor: globalTokens.blue,
    thumbHeight: "24px",
    thumbWidth: "24px",
    trackHeight: "12px",
    trackWidth: "60px",
    thumbTranslateX: "40%",
  },
  tag: {
    textDecoration: globalTokens.type_no_line,
  },
  table: {
    headerBackgroundColor: globalTokens.purple,
    headerFontColor: globalTokens.white,
    separatorColor: globalTokens.lightGrey,
    bodyBackgroundColor: globalTokens.white,
    bodyFontColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_02,
    fontWeight: globalTokens.type_regular,
  },
  tabs: {
    selectedFontColor: globalTokens.purple,
    selectedIconColor: globalTokens.purple,
    selectedUnderlineColor: globalTokens.purple,
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.darkGrey,
    disabledFontColor: globalTokens.mediumGrey,
    focusOutline: globalTokens.purple,
    divider: globalTokens.mediumGrey,
    hoverBackgroundColor: globalTokens.lightPurple,
    pressedBackgroundColor: globalTokens.mediumPurple,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
    fontWeight: globalTokens.type_semibold,
  },
  textarea: {
    fontColor: globalTokens.black,
    placeholderColor: globalTokens.lightGrey,
    disabledFontColor: globalTokens.lighterBlack,
    error: globalTokens.red,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_03,
  },
  toggleGroup: {
    selectedBackgroundColor: globalTokens.purple,
    disabledSelectedBackgroundColor: globalTokens.lighterPurple,
    selectedBackgroundHoverColor: globalTokens.black,
    selectedFontColor: globalTokens.white,
    selectedHoverFontColor: globalTokens.white,
    unselectedBackgroundColor: globalTokens.lightGrey,
    disabledUnselectedBackgroundColor: globalTokens.lightWhite,
    unselectedBackgroundHoverColor: globalTokens.darkWhite,
    unselectedFontColor: globalTokens.black,
    unselectedHoverFontColor: globalTokens.black,
    disabledUnselectedFontColor: globalTokens.lighterBlack,
    disabledSelectedFontColor: globalTokens.white,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize: globalTokens.type_scale_02,
    fontStyle: globalTokens.type_normal,
    fontTextTransform: globalTokens.type_uppercase,
    fontLetterSpacingWide02: globalTokens.type_spacing_wide_02,
  },
  upload: {
    fontColor: globalTokens.darkGrey,
    shadowColor: globalTokens.lightWhite,
    backgroundDragColor: globalTokens.lightWhite,
    accentColor: globalTokens.lightGrey,
    fileHoverColor: globalTokens.darkWhite,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    errorColor: globalTokens.red,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize20: globalTokens.type_scale_04,
    fontSize16: globalTokens.type_scale_03,
    fontSize12: globalTokens.type_scale_01,
    fontStyle: globalTokens.type_italic,
    fontTextTransform: globalTokens.type_uppercase,
    fontWeight: globalTokens.type_bold,
  },
  wizard: {
    selectedBackgroundColor: globalTokens.purple,
    selectedFont: globalTokens.white,
    borderColor: globalTokens.black,
    fontColor: globalTokens.inherit,
    lineColor: globalTokens.lightGrey,
    disabledBackground: globalTokens.lightGrey,
    disabledFont: globalTokens.darkGrey,
    fontFamily: globalTokens.type_sans,
    fontSizeBase: globalTokens.type_scale_root,
    fontSize16: globalTokens.type_scale_03,
    fontSize12: globalTokens.type_scale_01,
    fontStyle: globalTokens.type_normal,
    fontLetterSpacingWide01: globalTokens.type_spacing_wide_01,
    fontLetterSpacingWide02: globalTokens.type_spacing_wide_02,
  },
};
export const spaces = {
  xxsmall: "6px",
  xsmall: "16px",
  small: "24px",
  medium: "36px",
  large: "48px",
  xlarge: "64px",
  xxlarge: "100px",
};
export const responsiveSizes = {
  mobileSmall: "320",
  mobileMedium: "375",
  mobileLarge: "425",
  tablet: "768",
  laptop: "1024",
  desktop: "1440",
};
export const typeface = {
  body: {
    fontSize: "16px",
    letterSpacing: "0.5",
    textTransform: "initial",
  },
  altBody: {
    fontSize: "14px",
    letterSpacing: "0.25",
    textTransform: "initial",
  },
  subtitle: {
    fontSize: "16px",
    letterSpacing: "0.15",
    textTransform: "initial",
  },
  altSubtitle: {
    fontSize: "14px",
    letterSpacing: "0.1",
    textTransform: "initial",
  },
  caption: {
    fontSize: "12px",
    letterSpacing: "0.4",
    textTransform: "initial",
  },
  overline: {
    fontSize: "12px",
    letterSpacing: "2",
    textTransform: "uppercase",
  },
};
