import CoreTokens from "./coreTokens";

export const componentTokens = {
  accordion: {
    backgroundColor: CoreTokens.color_white,
    hoverBackgroundColor: CoreTokens.color_purple_100,
    arrowColor: CoreTokens.color_purple_700,
    disabledArrowColor: CoreTokens.color_grey_500,
    assistiveTextFontFamily: CoreTokens.type_sans,
    assistiveTextFontSize: CoreTokens.type_scale_03,
    assistiveTextFontWeight: CoreTokens.type_light,
    assistiveTextFontStyle: CoreTokens.type_italic,
    assistiveTextLetterSpacing: CoreTokens.type_spacing_wide_01,
    assistiveTextFontColor: CoreTokens.color_grey_700,
    disabledAssistiveTextFontColor: CoreTokens.color_grey_500,
    assistiveTextMinWidth: "100px",
    assistiveTextPaddingRight: CoreTokens.spacing_24,
    assistiveTextPaddingLeft: CoreTokens.spacing_0,
    titleLabelFontFamily: CoreTokens.type_sans,
    titleLabelFontSize: CoreTokens.type_scale_03,
    titleLabelFontWeight: CoreTokens.type_regular,
    titleLabelFontStyle: CoreTokens.type_normal,
    titleLabelFontColor: CoreTokens.color_black,
    disabledTitleLabelFontColor: CoreTokens.color_grey_500,
    titleLabelPaddingTop: CoreTokens.spacing_0,
    titleLabelPaddingBottom: CoreTokens.spacing_0,
    titleLabelPaddingLeft: CoreTokens.spacing_0,
    titleLabelPaddingRight: CoreTokens.spacing_16,
    focusBorderColor: CoreTokens.color_blue_600,
    focusBorderStyle: CoreTokens.border_solid,
    focusBorderThickness: "2px",
    borderRadius: "4px",
    boxShadowOffsetX: "0px",
    boxShadowOffsetY: "6px",
    boxShadowBlur: "10px",
    boxShadowColor: CoreTokens.color_grey_200_a,
    iconColor: CoreTokens.color_purple_700,
    disabledIconColor: CoreTokens.color_grey_500,
    iconSize: "24px",
    iconMarginLeft: CoreTokens.spacing_0,
    iconMarginRight: CoreTokens.spacing_12,
    accordionGroupSeparatorBorderColor: CoreTokens.color_grey_200_a,
    accordionGroupSeparatorBorderThickness: "1px",
    accordionGroupSeparatorBorderRadius: "0px",
    accordionGroupSeparatorBorderStyle: CoreTokens.border_solid,
  },
  alert: {
    titleFontFamily: CoreTokens.type_sans,
    titleFontColor: CoreTokens.color_black,
    titleFontSize: CoreTokens.type_scale_01,
    titleFontStyle: CoreTokens.type_normal,
    titleFontWeight: CoreTokens.type_bold,
    titleTextTransform: CoreTokens.type_uppercase,
    titlePaddingRight: CoreTokens.spacing_0,
    titlePaddingLeft: CoreTokens.spacing_0,
    inlineTextFontFamily: CoreTokens.type_sans,
    inlineTextFontColor: CoreTokens.color_black,
    inlineTextFontSize: CoreTokens.type_scale_01,
    inlineTextFontStyle: CoreTokens.type_normal,
    inlineTextFontWeight: CoreTokens.type_regular,
    inlineTextPaddingLeft: CoreTokens.spacing_0,
    inlineTextPaddingRight: CoreTokens.spacing_0,
    contentPaddingLeft: CoreTokens.spacing_0,
    contentPaddingRight: CoreTokens.spacing_0,
    contentPaddingTop: "20px",
    contentPaddingBottom: "30px",
    borderRadius: "4px",
    borderStyle: CoreTokens.border_solid,
    borderThickness: "1px",
    infoBorderColor: CoreTokens.color_blue_800,
    successBorderColor: CoreTokens.color_green_700,
    warningBorderColor: CoreTokens.color_yellow_700,
    errorBorderColor: CoreTokens.color_red_700,
    iconSize: "24px",
    iconPaddingLeft: CoreTokens.spacing_0,
    iconPaddingRight: CoreTokens.spacing_0,
    infoIconColor: CoreTokens.color_blue_800,
    successIconColor: CoreTokens.color_green_700,
    warningIconColor: CoreTokens.color_yellow_700,
    errorIconColor: CoreTokens.color_red_700,
    infoBackgroundColor: CoreTokens.color_blue_100,
    successBackgroundColor: CoreTokens.color_green_100,
    warningBackgroundColor: CoreTokens.color_yellow_100,
    errorBackgroundColor: CoreTokens.color_red_100,
    hoverActionBackgroundColor: CoreTokens.color_grey_100_a,
    activeActionBackgroundColor: CoreTokens.color_grey_200_a,
    focusActionBorderColor: CoreTokens.color_blue_600,
    overlayColor: CoreTokens.color_grey_800_a,
  },
  box: {
    backgroundColor: CoreTokens.color_white,
    borderRadius: CoreTokens.border_radius_medium,
    borderThickness: CoreTokens.border_width_0,
    borderStyle: CoreTokens.border_none,
    borderColor: CoreTokens.color_transparent,
    noneShadowDepthShadowOffsetX: "none",
    noneShadowDepthShadowOffsetY: "none",
    noneShadowDepthShadowBlur: "none",
    noneShadowDepthShadowSpread: "none",
    noneShadowDepthShadowColor: CoreTokens.color_transparent,
    oneShadowDepthShadowOffsetX: "0px",
    oneShadowDepthShadowOffsetY: "3px",
    oneShadowDepthShadowBlur: "6px",
    oneShadowDepthShadowSpread: "0px",
    oneShadowDepthShadowColor: CoreTokens.color_grey_300_a,
    twoShadowDepthShadowOffsetX: "0px",
    twoShadowDepthShadowOffsetY: "3px",
    twoShadowDepthShadowBlur: "10px",
    twoShadowDepthShadowSpread: "0px",
    twoShadowDepthShadowColor: CoreTokens.color_grey_300_a,
  },
  bulletedList: {
    fontColor: CoreTokens.color_black,
    bulletIconHeight: "1.5rem",
    bulletIconWidth: "1.5rem",
    bulletHeight: "5px",
    bulletWidth: "5px",
    bulletMarginRight: CoreTokens.spacing_8,
  },
  button: {
    labelFontLineHeight: CoreTokens.type_leading_normal,
    labelLetterSpacing: CoreTokens.type_spacing_wide_01,
    paddingLeft: CoreTokens.spacing_8,
    paddingRight: CoreTokens.spacing_8,
    paddingTop: CoreTokens.spacing_8,
    paddingBottom: CoreTokens.spacing_8,
    focusBorderColor: CoreTokens.color_blue_600,
    primaryBackgroundColor: CoreTokens.color_purple_700,
    primaryFontColor: CoreTokens.color_white,
    primaryHoverBackgroundColor: CoreTokens.color_purple_800,
    primaryActiveBackgroundColor: CoreTokens.color_purple_900,
    primaryDisabledBackgroundColor: CoreTokens.color_grey_100,
    primaryDisabledFontColor: CoreTokens.color_grey_500,
    primaryBorderThickness: CoreTokens.border_width_0,
    primaryBorderStyle: CoreTokens.border_none,
    primaryBorderRadius: CoreTokens.border_radius_medium,
    primaryFontFamily: CoreTokens.type_sans,
    primaryFontSize: CoreTokens.type_scale_03,
    primaryFontWeight: CoreTokens.type_regular,
    secondaryBackgroundColor: CoreTokens.color_transparent,
    secondaryFontColor: CoreTokens.color_purple_700,
    secondaryHoverFontColor: CoreTokens.color_white,
    secondaryBorderColor: CoreTokens.color_purple_700,
    secondaryHoverBackgroundColor: CoreTokens.color_purple_700,
    secondaryActiveBackgroundColor: CoreTokens.color_purple_900,
    secondaryDisabledBackgroundColor: CoreTokens.color_transparent,
    secondaryDisabledFontColor: CoreTokens.color_grey_500,
    secondaryDisabledBorderColor: CoreTokens.color_grey_500,
    secondaryBorderThickness: CoreTokens.border_width_1,
    secondaryBorderStyle: CoreTokens.border_solid,
    secondaryBorderRadius: CoreTokens.border_radius_medium,
    secondaryFontFamily: CoreTokens.type_sans,
    secondaryFontSize: CoreTokens.type_scale_03,
    secondaryFontWeight: CoreTokens.type_regular,
    textBackgroundColor: CoreTokens.color_transparent,
    textFontColor: CoreTokens.color_purple_700,
    textHoverBackgroundColor: CoreTokens.color_purple_100,
    textActiveBackgroundColor: CoreTokens.color_purple_200,
    textDisabledBackgroundColor: CoreTokens.color_transparent,
    textDisabledFontColor: CoreTokens.color_grey_500,
    textBorderThickness: CoreTokens.border_width_0,
    textBorderStyle: CoreTokens.border_none,
    textBorderRadius: CoreTokens.border_radius_medium,
    textFontFamily: CoreTokens.type_sans,
    textFontSize: CoreTokens.type_scale_03,
    textFontWeight: CoreTokens.type_regular,
  },
  card: {
    height: "220px",
    width: "400px",
  },
  checkbox: {
    backgroundColorChecked: CoreTokens.color_blue_800,
    hoverBackgroundColorChecked: CoreTokens.color_blue_900,
    disabledBackgroundColorChecked: CoreTokens.color_grey_500,
    readOnlyBackgroundColorChecked: CoreTokens.color_grey_500,
    hoverReadOnlyBackgroundColorChecked: CoreTokens.color_grey_600,
    borderColor: CoreTokens.color_blue_800,
    hoverBorderColor: CoreTokens.color_blue_900,
    disabledBorderColor: CoreTokens.color_grey_500,
    readOnlyBorderColor: CoreTokens.color_grey_500,
    hoverReadOnlyBorderColor: CoreTokens.color_grey_600,
    checkColor: CoreTokens.color_white,
    disabledCheckColor: CoreTokens.color_white,
    readOnlyCheckColor: CoreTokens.color_white,
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_02,
    fontWeight: CoreTokens.type_regular,
    fontColor: CoreTokens.color_black,
    disabledFontColor: CoreTokens.color_grey_500,
    focusColor: CoreTokens.color_blue_600,
    checkLabelSpacing: CoreTokens.spacing_8,
  },
  chip: {
    backgroundColor: CoreTokens.color_grey_200,
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_03,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
    fontColor: CoreTokens.color_black,
    disabledFontColor: CoreTokens.color_grey_500,
    borderColor: CoreTokens.color_transparent,
    borderRadius: "80px",
    borderThickness: CoreTokens.border_width_0,
    borderStyle: CoreTokens.border_solid,
    contentPaddingLeft: CoreTokens.spacing_16,
    contentPaddingRight: CoreTokens.spacing_16,
    contentPaddingTop: CoreTokens.spacing_0,
    contentPaddingBottom: CoreTokens.spacing_0,
    iconSize: "24px",
    iconSpacing: CoreTokens.spacing_8,
    iconColor: CoreTokens.color_grey_800,
    hoverIconColor: CoreTokens.color_grey_900,
    activeIconColor: CoreTokens.color_black,
    disabledIconColor: CoreTokens.color_grey_500,
    focusColor: CoreTokens.color_blue_600,
    focusBorderStyle: CoreTokens.border_solid,
    focusBorderThickness: CoreTokens.border_width_2,
    focusBorderRadius: CoreTokens.border_radius_medium,
  },
  dateInput: {
    pickerBackgroundColor: CoreTokens.color_white,
    pickerFontColor: CoreTokens.color_black,
    pickerBorderColor: CoreTokens.color_grey_400,
    pickerSelectedBackgroundColor: CoreTokens.color_purple_700,
    pickerSelectedFontColor: CoreTokens.color_white,
    pickerHoverBackgroundColor: CoreTokens.color_purple_200,
    pickerHoverFontColor: CoreTokens.color_black,
    pickerActiveBackgroundColor: CoreTokens.color_purple_800,
    pickerActiveFontColor: CoreTokens.color_white,
    pickerNonCurrentMonthFontColor: CoreTokens.color_grey_500,
    pickerCurrentDateBorderColor: CoreTokens.color_purple_300,
    pickerCurrentDateFontColor: CoreTokens.color_black,
    pickerCurrentYearFontColor: CoreTokens.color_purple_700,
    pickerHeaderBackgroundColor: CoreTokens.color_transparent,
    pickerHeaderFontColor: CoreTokens.color_black,
    pickerHeaderHoverBackgroundColor: CoreTokens.color_purple_200,
    pickerHeaderHoverFontColor: CoreTokens.color_black,
    pickerHeaderActiveBackgroundColor: CoreTokens.color_purple_800,
    pickerHeaderActiveFontColor: CoreTokens.color_white,
    pickerFocusColor: CoreTokens.color_blue_600,
    pickerBorderWidth: CoreTokens.border_width_1,
    pickerBorderStyle: CoreTokens.border_solid,
    pickerFocusWidth: CoreTokens.border_width_2,
    pickerCurrentDateBorderWidth: CoreTokens.border_width_1,
    pickerFontFamily: CoreTokens.type_sans,
    pickerFontSize: CoreTokens.type_scale_02,
    pickerFontWeight: CoreTokens.type_regular,
    pickerInteractedYearFontSize: CoreTokens.type_scale_05,
    pickerHeaderFontSize: CoreTokens.type_scale_02,
  },
  dialog: {
    overlayColor: CoreTokens.color_grey_800_a,
    backgroundColor: CoreTokens.color_white,
    closeIconSize: "24px",
    closeIconTopPosition: "20px",
    closeIconRightPosition: "20px",
    closeIconBackgroundColor: CoreTokens.color_transparent,
    closeIconBorderColor: CoreTokens.border_none,
    closeIconColor: CoreTokens.color_black,
    closeIconBorderThickness: CoreTokens.border_width_0,
    closeIconBorderStyle: CoreTokens.border_solid,
    closeIconBorderRadius: "2px",
    boxShadowOffsetX: "0px",
    boxShadowOffsetY: "1px",
    boxShadowBlur: "3px",
    boxShadowColor: CoreTokens.color_grey_300_a,
  },
  dropdown: {
    buttonBackgroundColor: CoreTokens.color_white,
    hoverButtonBackgroundColor: CoreTokens.color_grey_100,
    activeButtonBackgroundColor: CoreTokens.color_grey_300,
    buttonFontFamily: CoreTokens.type_sans,
    buttonFontSize: CoreTokens.type_scale_03,
    buttonFontStyle: CoreTokens.type_normal,
    buttonFontWeight: CoreTokens.type_regular,
    buttonFontColor: CoreTokens.color_black,
    buttonIconSize: "20px",
    buttonIconSpacing: "10px",
    buttonIconColor: CoreTokens.color_black,
    buttonPaddingTop: CoreTokens.spacing_0,
    buttonPaddingBottom: CoreTokens.spacing_0,
    buttonPaddingLeft: CoreTokens.spacing_16,
    buttonPaddingRight: CoreTokens.spacing_16,
    buttonHeight: "40px",
    buttonBorderRadius: "4px",
    buttonBorderStyle: CoreTokens.border_none,
    buttonBorderThickness: CoreTokens.border_width_0,
    buttonBorderColor: CoreTokens.color_transparent,
    disabledColor: CoreTokens.color_grey_500,
    disabledButtonBackgroundColor: CoreTokens.color_transparent,
    disabledButtonBorderColor: CoreTokens.color_transparent,
    optionBackgroundColor: CoreTokens.color_white,
    hoverOptionBackgroundColor: CoreTokens.color_grey_100,
    activeOptionBackgroundColor: CoreTokens.color_grey_300,
    optionFontFamily: CoreTokens.type_sans,
    optionFontSize: CoreTokens.type_scale_root,
    optionFontStyle: CoreTokens.type_normal,
    optionFontWeight: CoreTokens.type_regular,
    optionFontColor: CoreTokens.color_black,
    optionIconSize: "20px",
    optionIconSpacing: "10px",
    optionIconColor: CoreTokens.color_black,
    optionPaddingTop: "6px",
    optionPaddingBottom: "6px",
    optionPaddingLeft: CoreTokens.spacing_16,
    optionPaddingRight: CoreTokens.spacing_16,
    caretIconSize: "24px",
    caretIconColor: CoreTokens.color_black,
    caretIconSpacing: CoreTokens.spacing_12,
    borderRadius: "4px",
    borderStyle: CoreTokens.border_none,
    borderThickness: CoreTokens.border_width_0,
    borderColor: CoreTokens.color_transparent,
    scrollBarThumbColor: CoreTokens.color_grey_700,
    scrollBarTrackColor: CoreTokens.color_grey_300,
    focusColor: CoreTokens.color_blue_600,
  },
  fileInput: {
    dropBorderColor: CoreTokens.color_black,
    fileItemBorderColor: CoreTokens.color_grey_300,
    fileNameFontColor: CoreTokens.color_black,
    labelFontColor: CoreTokens.color_black,
    helperTextFontColor: CoreTokens.color_black,
    dropLabelFontColor: CoreTokens.color_black,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    disabledHelperTextFontcolor: CoreTokens.color_grey_500,
    disabledDropLabelFontColor: CoreTokens.color_grey_500,
    focusDropBorderColor: CoreTokens.color_blue_600,
    disabledDropBorderColor: CoreTokens.color_grey_500,
    dragoverDropBackgroundColor: CoreTokens.color_blue_50,
    errorFileItemBorderColor: CoreTokens.color_red_700,
    errorFileItemBackgroundColor: CoreTokens.color_red_50,
    errorFilePreviewBackgroundColor: CoreTokens.color_red_200,
    errorFileItemIconColor: CoreTokens.color_red_700,
    fileItemIconBackgroundColor: CoreTokens.color_grey_100,
    deleteFileItemColor: CoreTokens.color_black,
    errorMessageFontColor: CoreTokens.color_red_700,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    fileItemFontFamily: CoreTokens.type_sans,
    fileItemFontSize: CoreTokens.type_scale_02,
    fileItemFontWeight: CoreTokens.type_regular,
    fileItemLineHeight: CoreTokens.type_leading_normal,
    helperTextFontFamily: CoreTokens.type_sans,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    dropLabelFontFamily: CoreTokens.type_sans,
    dropLabelFontSize: CoreTokens.type_scale_03,
    dropLabelFontWeight: CoreTokens.type_regular,
    errorMessageFontFamily: CoreTokens.type_sans,
    errorMessageFontSize: CoreTokens.type_scale_01,
    errorMessageFontWeight: CoreTokens.type_regular,
    errorMessageLineHeight: CoreTokens.type_leading_normal,
    dropBorderThickness: CoreTokens.border_width_1,
    dropBorderStyle: CoreTokens.border_dashed,
    dropBorderRadius: CoreTokens.border_radius_large,
    fileItemBorderThickness: CoreTokens.border_width_1,
    fileItemBorderStyle: CoreTokens.border_solid,
    fileItemBorderRadius: CoreTokens.border_radius_medium,
    hoverDeleteFileItemBackgroundColor: CoreTokens.color_grey_100_a,
    activeDeleteFileItemBackgroundColor: CoreTokens.color_grey_300_a,
    focusDeleteFileItemBorderColor: CoreTokens.color_blue_600,
    filePreviewBackgroundColor: CoreTokens.color_grey_100,
    filePreviewIconColor: CoreTokens.color_grey_600,
    errorFilePreviewIconColor: CoreTokens.color_red_700,
  },
  footer: {
    height: "124px",
    backgroundColor: CoreTokens.color_black,
    bottomLinksDividerColor: CoreTokens.color_blue_600,
    bottomLinksDividerThickness: "1px",
    bottomLinksDividerStyle: CoreTokens.border_solid,
    bottomLinksDividerSpacing: CoreTokens.spacing_8,
    bottomLinksFontFamily: CoreTokens.type_sans,
    bottomLinksFontSize: CoreTokens.type_scale_01,
    bottomLinksFontStyle: CoreTokens.type_normal,
    bottomLinksFontWeight: CoreTokens.type_regular,
    bottomLinksFontColor: CoreTokens.color_white,
    bottomLinksTextDecoration: CoreTokens.type_no_line,
    copyrightFontFamily: CoreTokens.type_sans,
    copyrightFontSize: CoreTokens.type_scale_01,
    copyrightFontStyle: CoreTokens.type_normal,
    copyrightFontWeight: CoreTokens.type_regular,
    copyrightFontColor: CoreTokens.color_white,
    logo: "",
    logoHeight: "32px",
    logoWidth: "auto",
    socialLinksSize: "24px",
    socialLinksGutter: CoreTokens.spacing_16,
    socialLinksColor: CoreTokens.color_white,
  },
  header: {
    backgroundColor: CoreTokens.color_white,
    hamburguerFocusColor: CoreTokens.color_blue_600,
    hamburguerFontFamily: CoreTokens.type_sans,
    hamburguerFontStyle: CoreTokens.type_normal,
    hamburguerFontColor: CoreTokens.color_black,
    hamburguerFontSize: "10px",
    hamburguerFontWeight: CoreTokens.type_semibold,
    hamburguerTextTransform: CoreTokens.type_uppercase,
    hamburguerIconColor: CoreTokens.color_black,
    hamburguerHoverColor: CoreTokens.color_grey_200,
    logo: "",
    logoResponsive: "",
    logoHeight: "40px",
    logoWidth: "auto",
    menuBackgroundColor: CoreTokens.color_white,
    menuZindex: "2000",
    menuTabletWidth: "60vw",
    menuMobileWidth: "100vw",
    minHeight: "64px",
    overlayColor: CoreTokens.color_grey_800_a,
    overlayOpacity: "0.7",
    overlayZindex: "1600",
    paddingTop: CoreTokens.spacing_0,
    paddingBottom: CoreTokens.spacing_0,
    paddingRight: CoreTokens.spacing_24,
    paddingLeft: CoreTokens.spacing_24,
    underlinedColor: CoreTokens.color_black,
    underlinedThickness: "2px",
    underlinedStyle: CoreTokens.border_solid,
    contentColor: CoreTokens.color_black,
  },
  heading: {
    level1FontColor: CoreTokens.inherit,
    level1FontFamily: CoreTokens.type_sans,
    level1FontSize: CoreTokens.type_scale_07,
    level1FontStyle: CoreTokens.type_normal,
    level1FontWeight: CoreTokens.type_semibold,
    level1LineHeight: CoreTokens.type_leading_compact_01,
    level1LetterSpacing: CoreTokens.type_spacing_tight_01,
    level2FontColor: CoreTokens.inherit,
    level2FontFamily: CoreTokens.type_sans,
    level2FontSize: CoreTokens.type_scale_05,
    level2FontStyle: CoreTokens.type_normal,
    level2FontWeight: CoreTokens.type_semibold,
    level2LineHeight: CoreTokens.type_leading_normal,
    level2LetterSpacing: CoreTokens.type_spacing_normal,
    level3FontColor: CoreTokens.inherit,
    level3FontFamily: CoreTokens.type_sans,
    level3FontSize: CoreTokens.type_scale_04,
    level3FontStyle: CoreTokens.type_normal,
    level3FontWeight: CoreTokens.type_semibold,
    level3LineHeight: CoreTokens.type_leading_compact_01,
    level3LetterSpacing: CoreTokens.type_spacing_wide_01,
    level4FontColor: CoreTokens.inherit,
    level4FontFamily: CoreTokens.type_sans,
    level4FontSize: CoreTokens.type_scale_03,
    level4FontStyle: CoreTokens.type_normal,
    level4FontWeight: CoreTokens.type_semibold,
    level4LineHeight: CoreTokens.type_leading_normal,
    level4LetterSpacing: CoreTokens.type_spacing_normal,
    level5FontColor: CoreTokens.inherit,
    level5FontFamily: CoreTokens.type_sans,
    level5FontSize: CoreTokens.type_scale_02,
    level5FontStyle: CoreTokens.type_normal,
    level5FontWeight: CoreTokens.type_semibold,
    level5LineHeight: CoreTokens.type_leading_normal,
    level5LetterSpacing: CoreTokens.type_spacing_wide_01,
  },
  image: {
    captionFontColor: CoreTokens.color_grey_900,
    captionFontFamily: CoreTokens.type_sans,
    captionFontSize: CoreTokens.type_scale_02,
    captionFontStyle: CoreTokens.type_normal,
    captionFontWeight: CoreTokens.type_regular,
    captionLineHeight: CoreTokens.type_leading_normal,
  },
  link: {
    fontColor: CoreTokens.color_blue_800,
    fontFamily: CoreTokens.inherit,
    fontSize: CoreTokens.inherit,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
    iconSize: "16px",
    iconSpacing: CoreTokens.spacing_4,
    underlineSpacing: CoreTokens.spacing_0,
    underlineStyle: CoreTokens.border_solid,
    underlineThickness: "1px",
    disabledFontColor: CoreTokens.color_grey_500,
    hoverFontColor: CoreTokens.color_blue_800,
    hoverUnderlineColor: CoreTokens.color_blue_800,
    visitedFontColor: CoreTokens.color_purple_700,
    visitedUnderlineColor: CoreTokens.color_purple_700,
    activeFontColor: CoreTokens.color_black,
    activeUnderlineColor: CoreTokens.color_black,
    focusColor: CoreTokens.color_blue_600,
  },
  navTabs: {
    selectedBackgroundColor: CoreTokens.color_white,
    unselectedBackgroundColor: CoreTokens.color_white,
    hoverBackgroundColor: CoreTokens.color_grey_100,
    pressedBackgroundColor: CoreTokens.color_grey_200,
    selectedFontColor: CoreTokens.color_grey_700,
    unselectedFontColor: CoreTokens.color_grey_700,
    disabledFontColor: CoreTokens.color_grey_500,
    focusOutline: CoreTokens.color_blue_600,
    selectedUnderlineColor: CoreTokens.color_purple_700,
    dividerColor: CoreTokens.color_grey_400,
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_03,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
    selectedIconColor: CoreTokens.color_grey_700,
    unselectedIconColor: CoreTokens.color_grey_700,
    disabledIconColor: CoreTokens.color_grey_500,
  },
  paginator: {
    backgroundColor: CoreTokens.color_grey_100,
    fontColor: CoreTokens.color_black,
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_02,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
    fontTextTransform: "none",
    verticalPadding: CoreTokens.spacing_12,
    horizontalPadding: CoreTokens.spacing_32,
    marginRight: CoreTokens.spacing_40,
    marginLeft: "20px",
    itemsPerPageSelectorMarginLeft: CoreTokens.spacing_0,
    itemsPerPageSelectorMarginRight: CoreTokens.spacing_8,
    pageSelectorMarginRight: "30px",
    pageSelectorMarginLeft: CoreTokens.spacing_0,
    totalItemsContainerMarginRight: CoreTokens.spacing_40,
    totalItemsContainerMarginLeft: CoreTokens.spacing_0,
  },
  paragraph: {
    display: "block",
    fontColor: CoreTokens.color_black,
    fontSize: CoreTokens.type_scale_03,
    fontWeight: CoreTokens.type_regular,
  },
  progressBar: {
    trackLineColor: CoreTokens.color_purple_700,
    totalLineColor: CoreTokens.color_grey_200,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_01,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_regular,
    labelFontColor: CoreTokens.color_black,
    labelFontTextTransform: CoreTokens.type_uppercase,
    valueFontFamily: CoreTokens.type_sans,
    valueFontSize: CoreTokens.type_scale_01,
    valueFontStyle: CoreTokens.type_normal,
    valueFontWeight: CoreTokens.type_regular,
    valueFontColor: CoreTokens.color_black,
    valueFontTextTransform: CoreTokens.type_uppercase,
    helperTextFontColor: CoreTokens.color_black,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextFontFamily: CoreTokens.type_sans,
    thickness: "9px",
    borderRadius: "5px",
    overlayColor: CoreTokens.color_grey_800_a,
    overlayFontColor: CoreTokens.color_white,
  },
  quickNav: {
    fontColor: CoreTokens.color_grey_700,
    hoverFontColor: CoreTokens.color_purple_600,
    dividerBorderColor: CoreTokens.color_grey_400,
    focusBorderColor: CoreTokens.color_blue_600,
    focusBorderStyle: CoreTokens.border_solid,
    focusBorderThickness: CoreTokens.border_width_2,
    focusBorderRadius: CoreTokens.border_width_2,
    paddingTop: CoreTokens.spacing_8,
    paddingBottom: CoreTokens.spacing_8,
    paddingLeft: CoreTokens.spacing_16,
    paddingRight: CoreTokens.spacing_16,
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_02,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
  },
  radioGroup: {
    fontFamily: CoreTokens.type_sans,
    radioInputColor: CoreTokens.color_blue_700,
    hoverRadioInputColor: CoreTokens.color_blue_800,
    focusBorderColor: CoreTokens.color_blue_600,
    activeRadioInputColor: CoreTokens.color_blue_900,
    errorRadioInputColor: CoreTokens.color_red_700,
    hoverErrorRadioInputColor: CoreTokens.color_red_800,
    activeErrorRadioInputColor: CoreTokens.color_red_900,
    readOnlyRadioInputColor: CoreTokens.color_grey_500,
    hoverReadOnlyRadioInputColor: CoreTokens.color_grey_600,
    activeReadOnlyRadioInputColor: CoreTokens.color_grey_700,
    disabledRadioInputColor: CoreTokens.color_grey_500,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    disabledHelperTextFontColor: CoreTokens.color_grey_500,
    disabledRadioInputLabelFontColor: CoreTokens.color_grey_500,
    errorMessageColor: CoreTokens.color_red_700,
    labelFontColor: CoreTokens.color_black,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    optionalLabelFontWeight: CoreTokens.type_regular,
    helperTextFontColor: CoreTokens.color_black,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    radioInputLabelFontColor: CoreTokens.color_black,
    radioInputLabelFontSize: CoreTokens.type_scale_02,
    radioInputLabelFontStyle: CoreTokens.type_normal,
    radioInputLabelFontWeight: CoreTokens.type_regular,
    radioInputLabelLineHeight: CoreTokens.type_leading_loose_01,
    groupLabelMargin: CoreTokens.spacing_8,
    radioInputLabelMargin: CoreTokens.spacing_8,
    groupVerticalGutter: CoreTokens.spacing_4,
    groupHorizontalGutter: CoreTokens.spacing_32,
  },
  select: {
    fontFamily: CoreTokens.type_sans,
    disabledColor: CoreTokens.color_grey_500,
    enabledInputBorderColor: CoreTokens.color_black,
    hoverInputBorderColor: CoreTokens.color_purple_500,
    focusInputBorderColor: CoreTokens.color_blue_600,
    errorInputBorderColor: CoreTokens.color_red_700,
    hoverInputErrorBorderColor: CoreTokens.color_red_600,
    disabledInputBorderColor: CoreTokens.color_grey_500,
    disabledInputBackgroundColor: CoreTokens.color_grey_100,
    inputMarginTop: CoreTokens.spacing_4,
    inputMarginBottom: CoreTokens.spacing_4,
    errorMessageColor: CoreTokens.color_red_700,
    errorIconColor: CoreTokens.color_red_700,
    labelFontColor: CoreTokens.color_black,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    optionalLabelFontWeight: CoreTokens.type_regular,
    helperTextFontColor: CoreTokens.color_black,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    placeholderFontColor: CoreTokens.color_grey_800_a,
    valueFontColor: CoreTokens.color_black,
    valueFontSize: CoreTokens.type_scale_03,
    valueFontStyle: CoreTokens.type_normal,
    valueFontWeight: CoreTokens.type_regular,
    actionIconColor: CoreTokens.color_black,
    hoverActionIconColor: CoreTokens.color_black,
    activeActionIconColor: CoreTokens.color_black,
    actionBackgroundColor: CoreTokens.color_transparent,
    hoverActionBackgroundColor: CoreTokens.color_grey_100,
    activeActionBackgroundColor: CoreTokens.color_grey_300,
    listOptionFontColor: CoreTokens.color_black,
    listOptionFontSize: CoreTokens.type_scale_02,
    listOptionFontStyle: CoreTokens.type_normal,
    listOptionFontWeight: CoreTokens.type_regular,
    listOptionIconColor: CoreTokens.color_black,
    listOptionDividerColor: CoreTokens.color_grey_200,
    listGroupLabelFontWeight: CoreTokens.type_semibold,
    focusListOptionBorderColor: CoreTokens.color_blue_600,
    systemMessageFontColor: CoreTokens.color_grey_700,
    collapseIndicatorColor: CoreTokens.color_black,
    listDialogBackgroundColor: CoreTokens.color_white,
    listDialogBorderColor: CoreTokens.color_grey_400,
    selectedListOptionBackgroundColor: CoreTokens.color_blue_100,
    selectedHoverListOptionBackgroundColor: CoreTokens.color_blue_200,
    selectedActiveListOptionBackgroundColor: CoreTokens.color_blue_300,
    selectedListOptionIconColor: CoreTokens.color_blue_900,
    unselectedHoverListOptionBackgroundColor: CoreTokens.color_grey_100,
    unselectedActiveListOptionBackgroundColor: CoreTokens.color_grey_200,
    selectionIndicatorFontColor: CoreTokens.color_black,
    selectionIndicatorFontSize: CoreTokens.type_scale_01,
    selectionIndicatorFontStyle: CoreTokens.type_regular,
    selectionIndicatorFontWeight: CoreTokens.type_normal,
    selectionIndicatorBorderColor: CoreTokens.color_grey_400,
    selectionIndicatorBackgroundColor: CoreTokens.color_grey_50,
    enabledSelectionIndicatorActionBackgroundColor: CoreTokens.color_transparent,
    enabledSelectionIndicatorActionIconColor: CoreTokens.color_black,
    hoverSelectionIndicatorActionBackgroundColor: CoreTokens.color_grey_100,
    hoverSelectionIndicatorActionIconColor: CoreTokens.color_black,
    activeSelectionIndicatorActionBackgroundColor: CoreTokens.color_grey_300,
    activeSelectionIndicatorActionIconColor: CoreTokens.color_black,
  },
  sidenav: {
    backgroundColor: CoreTokens.color_grey_100,
    titleFontFamily: CoreTokens.type_sans,
    titleFontSize: CoreTokens.type_scale_04,
    titleFontStyle: CoreTokens.type_normal,
    titleFontWeight: CoreTokens.type_semibold,
    titleFontColor: CoreTokens.color_grey_800,
    titleFontTextTransform: "none",
    titleFontLetterSpacing: CoreTokens.type_spacing_normal,
    groupTitleFontFamily: CoreTokens.type_sans,
    groupTitleFontSize: CoreTokens.type_scale_02,
    groupTitleFontStyle: CoreTokens.type_normal,
    groupTitleFontWeight: CoreTokens.type_semibold,
    groupTitleFontColor: CoreTokens.color_black,
    groupTitleHoverBackgroundColor: CoreTokens.color_grey_200,
    groupTitleActiveBackgroundColor: CoreTokens.color_grey_800,
    groupTitleSelectedFontColor: CoreTokens.color_white,
    groupTitleSelectedBackgroundColor: CoreTokens.color_grey_800,
    groupTitleSelectedHoverFontColor: CoreTokens.color_white,
    groupTitleSelectedHoverBackgroundColor: CoreTokens.color_grey_900,
    groupTitleFontTextTransform: CoreTokens.type_uppercase,
    groupTitleFontLetterSpacing: CoreTokens.type_spacing_wide_02,
    linkFontFamily: CoreTokens.type_sans,
    linkFontSize: CoreTokens.type_scale_02,
    linkFontStyle: CoreTokens.type_normal,
    linkFontWeight: CoreTokens.type_regular,
    linkFontColor: CoreTokens.color_grey_800,
    linkHoverBackgroundColor: CoreTokens.color_grey_200,
    linkSelectedFontColor: CoreTokens.color_white,
    linkSelectedBackgroundColor: CoreTokens.color_grey_800,
    linkSelectedHoverFontColor: CoreTokens.color_white,
    linkSelectedHoverBackgroundColor: CoreTokens.color_grey_900,
    linkFontTextTransform: "none",
    linkFontLetterSpacing: CoreTokens.type_spacing_wide_01,
    linkTextDecoration: CoreTokens.type_no_line,
    linkMarginTop: CoreTokens.spacing_4,
    linkMarginBottom: CoreTokens.spacing_4,
    linkMarginRight: CoreTokens.spacing_16,
    linkMarginLeft: CoreTokens.spacing_16,
    linkFocusColor: CoreTokens.color_blue_600,
    scrollBarThumbColor: CoreTokens.color_grey_200_a,
    scrollBarTrackColor: CoreTokens.color_transparent,
  },
  slider: {
    fontFamily: CoreTokens.type_sans,
    limitValuesFontColor: CoreTokens.color_black,
    limitValuesFontSize: CoreTokens.type_scale_03,
    limitValuesFontStyle: CoreTokens.type_normal,
    limitValuesFontWeight: CoreTokens.type_regular,
    limitValuesFontLetterSpacing: CoreTokens.type_spacing_normal,
    disabledLimitValuesFontColor: CoreTokens.color_grey_500,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    helperTextFontFamily: CoreTokens.type_sans,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    fontColor: CoreTokens.color_black,
    labelFontColor: CoreTokens.color_black,
    helperTextFontColor: CoreTokens.color_black,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    disabledHelperTextFontColor: CoreTokens.color_grey_500,
    thumbHeight: "12px",
    thumbWidth: "12px",
    hoverThumbHeight: "14px",
    hoverThumbWidth: "14px",
    thumbVerticalPosition: "12px",
    hoverThumbVerticalPosition: "11px",
    thumbBackgroundColor: CoreTokens.color_blue_800,
    hoverThumbScale: "1.166666",
    hoverThumbBackgroundColor: CoreTokens.color_blue_900,
    activeThumbScale: "1.166666",
    activeThumbBackgroundColor: CoreTokens.color_blue_900,
    focusThumbBackgroundColor: CoreTokens.color_blue_800,
    tickHeight: "4px",
    tickWidth: "4px",
    tickVerticalPosition: "11px",
    tickBackgroundColor: CoreTokens.color_blue_800,
    trackLineThickness: "2px",
    trackLineVerticalPosition: "50%",
    trackLineColor: CoreTokens.color_blue_800,
    totalLineThickness: "2px",
    totalLineVerticalPosition: "50%",
    totalLineColor: CoreTokens.color_grey_200_a,
    disabledThumbVerticalPosition: "10px",
    disabledThumbBackgroundColor: CoreTokens.color_grey_500,
    disabledTickVerticalPosition: "11px",
    disabledTickBackgroundColor: CoreTokens.color_grey_500,
    disabledTrackLineColor: CoreTokens.color_grey_500,
    disabledTotalLineColor: CoreTokens.color_grey_100,
    focusColor: CoreTokens.color_blue_600,
    floorLabelMarginRight: CoreTokens.type_scale_03,
    ceilLabelMarginLeft: CoreTokens.type_scale_03,
    inputMarginLeft: CoreTokens.type_scale_06,
  },
  spinner: {
    trackCircleColor: CoreTokens.color_purple_700,
    trackCircleColorOverlay: CoreTokens.color_purple_500,
    totalCircleColor: CoreTokens.color_white,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_regular,
    labelFontColor: CoreTokens.color_black,
    labelTextAlign: "center",
    progressValueFontFamily: CoreTokens.type_sans,
    progressValueFontSize: CoreTokens.type_scale_02,
    progressValueFontStyle: CoreTokens.type_normal,
    progressValueFontWeight: CoreTokens.type_bold,
    progressValueFontColor: CoreTokens.inherit,
    progressValueTextAlign: "center",
    overlayBackgroundColor: CoreTokens.color_black,
    overlayOpacity: "0.8",
    overlayLabelFontFamily: CoreTokens.type_sans,
    overlayLabelFontSize: CoreTokens.type_scale_02,
    overlayLabelFontStyle: CoreTokens.type_normal,
    overlayLabelFontWeight: CoreTokens.type_regular,
    overlayLabelFontColor: CoreTokens.color_white,
    overlayLabelTextAlign: "center",
    overlayProgressValueFontFamily: CoreTokens.type_sans,
    overlayProgressValueFontSize: CoreTokens.type_scale_02,
    overlayProgressValueFontStyle: CoreTokens.type_normal,
    overlayProgressValueFontWeight: CoreTokens.type_bold,
    overlayProgressValueFontColor: CoreTokens.color_white,
    overlayProgressValueTextAlign: "center",
  },
  switch: {
    checkedTrackBackgroundColor: CoreTokens.color_purple_700,
    checkedThumbBackgroundColor: CoreTokens.color_white,
    uncheckedTrackBackgroundColor: CoreTokens.color_grey_400,
    uncheckedThumbBackgroundColor: CoreTokens.color_white,
    disabledCheckedTrackBackgroundColor: CoreTokens.color_purple_100,
    disabledCheckedThumbBackgroundColor: CoreTokens.color_white,
    disabledUncheckedTrackBackgroundColor: CoreTokens.color_grey_100,
    disabledUncheckedThumbBackgroundColor: CoreTokens.color_white,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    disabledLabelFontStyle: CoreTokens.type_normal,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_root,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_regular,
    labelFontColor: CoreTokens.color_black,
    thumbFocusColor: CoreTokens.color_blue_600,
    thumbHeight: "24px",
    thumbWidth: "24px",
    thumbShift: "1.25rem",
    trackHeight: "12px",
    trackWidth: "36px",
    spaceBetweenLabelSwitch: CoreTokens.spacing_8,
  },
  table: {
    rowSeparatorThickness: "1px",
    rowSeparatorStyle: CoreTokens.border_solid,
    rowSeparatorColor: CoreTokens.color_grey_300,
    dataBackgroundColor: CoreTokens.color_white,
    dataFontFamily: CoreTokens.type_sans,
    dataFontSize: CoreTokens.type_scale_02,
    dataFontStyle: CoreTokens.type_normal,
    dataFontWeight: CoreTokens.type_regular,
    dataFontColor: CoreTokens.color_black,
    dataFontTextTransform: "none",
    dataPaddingTop: CoreTokens.spacing_16,
    dataPaddingBottom: CoreTokens.spacing_16,
    dataPaddingRight: "20px",
    dataPaddingLeft: "20px",
    dataPaddingTopReduced: CoreTokens.spacing_8,
    dataPaddingBottomReduced: CoreTokens.spacing_8,
    dataPaddingRightReduced: CoreTokens.spacing_16,
    dataPaddingLeftReduced: CoreTokens.spacing_16,
    dataTextAlign: "left",
    dataTextLineHeight: "normal",
    firstChildPaddingLeft: CoreTokens.spacing_24,
    lastChildPaddingRight: CoreTokens.spacing_24,
    firstChildPaddingLeftReduced: "20px",
    lastChildPaddingRightReduced: "20px",
    headerBackgroundColor: CoreTokens.color_purple_700,
    headerBorderRadius: "4px",
    headerFontFamily: CoreTokens.type_sans,
    headerFontSize: CoreTokens.type_scale_02,
    headerFontStyle: CoreTokens.type_normal,
    headerFontWeight: CoreTokens.type_regular,
    headerFontColor: CoreTokens.color_white,
    headerFontTextTransform: "none",
    headerPaddingTop: CoreTokens.spacing_16,
    headerPaddingBottom: CoreTokens.spacing_16,
    headerPaddingRight: "20px",
    headerPaddingLeft: "20px",
    headerPaddingTopReduced: CoreTokens.spacing_8,
    headerPaddingBottomReduced: CoreTokens.spacing_8,
    headerPaddingRightReduced: CoreTokens.spacing_16,
    headerPaddingLeftReduced: CoreTokens.spacing_16,
    headerTextAlign: "left",
    headerTextLineHeight: "normal",
    scrollBarThumbColor: CoreTokens.color_grey_700,
    scrollBarTrackColor: CoreTokens.color_grey_300,
    sortIconColor: CoreTokens.color_white,
    actionIconColor: CoreTokens.color_purple_700,
    disabledActionIconColor: CoreTokens.color_grey_500,
    hoverActionIconColor: CoreTokens.color_purple_700,
    focusActionIconColor: CoreTokens.color_purple_700,
    activeActionIconColor: CoreTokens.color_purple_700,
    actionBackgroundColor: CoreTokens.color_transparent,
    disabledActionBackgroundColor: CoreTokens.color_transparent,
    hoverActionBackgroundColor: CoreTokens.color_grey_100,
    focusActionBorderColor: CoreTokens.color_blue_600,
    activeActionBackgroundColor: CoreTokens.color_grey_300,
  },
  tabs: {
    fontFamily: CoreTokens.type_sans,
    fontSize: CoreTokens.type_scale_03,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_semibold,
    fontTextTransform: "none",
    selectedBackgroundColor: CoreTokens.color_white,
    selectedFontColor: CoreTokens.color_purple_700,
    selectedIconColor: CoreTokens.color_purple_700,
    selectedUnderlineColor: CoreTokens.color_purple_700,
    selectedUnderlineThickness: "2px",
    unselectedBackgroundColor: CoreTokens.color_white,
    unselectedFontColor: CoreTokens.color_grey_700,
    unselectedIconColor: CoreTokens.color_grey_700,
    disabledFontColor: CoreTokens.color_grey_500,
    disabledIconColor: CoreTokens.color_grey_500,
    disabledFontStyle: CoreTokens.type_normal,
    hoverBackgroundColor: CoreTokens.color_purple_100,
    pressedBackgroundColor: CoreTokens.color_purple_200,
    pressedFontWeight: CoreTokens.type_semibold,
    dividerColor: CoreTokens.color_grey_400,
    dividerThickness: "1px",
    focusOutline: CoreTokens.color_purple_700,
    scrollButtonsWidth: "48px",
  },
  tag: {
    fontFamily: CoreTokens.type_sans,
    fontColor: CoreTokens.color_black,
    fontSize: CoreTokens.type_scale_02,
    fontStyle: CoreTokens.type_normal,
    fontWeight: CoreTokens.type_regular,
    labelPaddingTop: CoreTokens.spacing_0,
    labelPaddingBottom: CoreTokens.spacing_0,
    labelPaddingLeft: CoreTokens.spacing_16,
    labelPaddingRight: CoreTokens.spacing_16,
    height: "40px",
    iconColor: CoreTokens.color_white,
    iconSectionWidth: "40px",
    iconHeight: "24px",
    iconWidth: "auto",
    focusColor: CoreTokens.color_blue_600,
  },
  textarea: {
    fontFamily: CoreTokens.type_sans,
    enabledBorderColor: CoreTokens.color_black,
    hoverBorderColor: CoreTokens.color_purple_500,
    focusBorderColor: CoreTokens.color_blue_600,
    disabledBorderColor: CoreTokens.color_grey_500,
    disabledContainerFillColor: CoreTokens.color_grey_100,
    readOnlyBorderColor: CoreTokens.color_grey_500,
    hoverReadOnlyBorderColor: CoreTokens.color_grey_600,
    errorBorderColor: CoreTokens.color_red_700,
    hoverErrorBorderColor: CoreTokens.color_red_600,
    inputMarginTop: CoreTokens.spacing_4,
    inputMarginBottom: CoreTokens.spacing_4,
    errorMessageColor: CoreTokens.color_red_700,
    labelFontColor: CoreTokens.color_black,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    optionalLabelFontWeight: CoreTokens.type_regular,
    helperTextFontColor: CoreTokens.color_black,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    disabledHelperTextFontColor: CoreTokens.color_grey_500,
    placeholderFontColor: CoreTokens.color_grey_800_a,
    disabledPlaceholderFontColor: CoreTokens.color_grey_500,
    valueFontColor: CoreTokens.color_black,
    valueFontSize: CoreTokens.type_scale_03,
    valueFontStyle: CoreTokens.type_normal,
    valueFontWeight: CoreTokens.type_regular,
    disabledValueFontColor: CoreTokens.color_grey_500,
  },
  textInput: {
    fontFamily: CoreTokens.type_sans,
    enabledBorderColor: CoreTokens.color_black,
    hoverBorderColor: CoreTokens.color_purple_500,
    focusBorderColor: CoreTokens.color_blue_600,
    disabledBorderColor: CoreTokens.color_grey_500,
    disabledContainerFillColor: CoreTokens.color_grey_100,
    readOnlyBorderColor: CoreTokens.color_grey_500,
    hoverReadOnlyBorderColor: CoreTokens.color_grey_600,
    errorBorderColor: CoreTokens.color_red_700,
    hoverErrorBorderColor: CoreTokens.color_red_600,
    inputMarginTop: CoreTokens.spacing_4,
    inputMarginBottom: CoreTokens.spacing_4,
    errorMessageColor: CoreTokens.color_red_700,
    errorIconColor: CoreTokens.color_red_700,
    labelFontColor: CoreTokens.color_black,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    optionalLabelFontWeight: CoreTokens.type_regular,
    helperTextFontColor: CoreTokens.color_black,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    disabledHelperTextFontColor: CoreTokens.color_grey_500,
    prefixColor: CoreTokens.color_grey_700,
    suffixColor: CoreTokens.color_grey_700,
    disabledPrefixColor: CoreTokens.color_grey_400,
    disabledSuffixColor: CoreTokens.color_grey_400,
    placeholderFontColor: CoreTokens.color_grey_800_a,
    disabledPlaceholderFontColor: CoreTokens.color_grey_500,
    valueFontColor: CoreTokens.color_black,
    valueFontSize: CoreTokens.type_scale_03,
    valueFontStyle: CoreTokens.type_normal,
    valueFontWeight: CoreTokens.type_regular,
    disabledValueFontColor: CoreTokens.color_grey_500,
    actionIconColor: CoreTokens.color_black,
    disabledActionIconColor: CoreTokens.color_grey_500,
    hoverActionIconColor: CoreTokens.color_black,
    focusActionIconColor: CoreTokens.color_black,
    activeActionIconColor: CoreTokens.color_black,
    actionBackgroundColor: CoreTokens.color_transparent,
    disabledActionBackgroundColor: CoreTokens.color_transparent,
    hoverActionBackgroundColor: CoreTokens.color_grey_100,
    focusActionBorderColor: CoreTokens.color_blue_600,
    activeActionBackgroundColor: CoreTokens.color_grey_300,
    listDialogBackgroundColor: CoreTokens.color_white,
    listDialogBorderColor: CoreTokens.color_grey_400,
    listOptionDividerColor: CoreTokens.color_grey_200,
    listOptionFontColor: CoreTokens.color_black,
    listOptionFontSize: CoreTokens.type_scale_02,
    listOptionFontStyle: CoreTokens.type_normal,
    listOptionFontWeight: CoreTokens.type_regular,
    systemMessageFontColor: CoreTokens.color_grey_700,
    errorListDialogFontColor: CoreTokens.color_black,
    errorListDialogBackgroundColor: CoreTokens.color_red_50,
    errorListDialogBorderColor: CoreTokens.color_red_700,
    hoverListOptionBackgroundColor: CoreTokens.color_grey_100,
    activeListOptionBackgroundColor: CoreTokens.color_grey_200,
    focusListOptionBorderColor: CoreTokens.color_blue_600,
  },
  toggleGroup: {
    containerBackgroundColor: CoreTokens.color_grey_50,
    containerBorderColor: CoreTokens.color_grey_500,
    labelFontColor: CoreTokens.color_black,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    helperTextFontColor: CoreTokens.color_black,
    disabledHelperTextFontcolor: CoreTokens.color_grey_500,
    unselectedBackgroundColor: CoreTokens.color_grey_200,
    unselectedHoverBackgroundColor: CoreTokens.color_grey_300,
    unselectedActiveBackgroundColor: CoreTokens.color_purple_700,
    unselectedDisabledBackgroundColor: CoreTokens.color_grey_100,
    unselectedFontColor: CoreTokens.color_black,
    unselectedDisabledFontColor: CoreTokens.color_grey_500,
    selectedBackgroundColor: CoreTokens.color_purple_700,
    selectedHoverBackgroundColor: CoreTokens.color_purple_800,
    selectedActiveBackgroundColor: CoreTokens.color_purple_900,
    selectedDisabledBackgroundColor: CoreTokens.color_purple_100,
    selectedFontColor: CoreTokens.color_white,
    selectedDisabledFontColor: CoreTokens.color_purple_300,
    focusColor: CoreTokens.color_blue_600,
    labelFontFamily: CoreTokens.type_sans,
    labelFontSize: CoreTokens.type_scale_02,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_semibold,
    labelLineHeight: CoreTokens.type_leading_loose_01,
    helperTextFontFamily: CoreTokens.type_sans,
    helperTextFontSize: CoreTokens.type_scale_01,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextLineHeight: CoreTokens.type_leading_normal,
    optionLabelFontFamily: CoreTokens.type_sans,
    optionLabelFontSize: CoreTokens.type_scale_03,
    optionLabelFontStyle: CoreTokens.type_normal,
    optionLabelFontWeight: CoreTokens.type_regular,
    iconPaddingRight: CoreTokens.spacing_8,
    iconPaddingLeft: CoreTokens.spacing_8,
    labelPaddingLeft: CoreTokens.spacing_24,
    labelPaddingRight: CoreTokens.spacing_24,
    iconMarginRight: CoreTokens.spacing_8,
    containerMarginTop: CoreTokens.spacing_4,
    optionBorderThickness: CoreTokens.border_width_0,
    optionBorderStyle: CoreTokens.border_none,
    optionBorderRadius: CoreTokens.border_radius_medium,
    containerBorderThickness: CoreTokens.border_width_1,
    containerBorderStyle: CoreTokens.border_solid,
    containerBorderRadius: CoreTokens.border_radius_large,
    optionFocusBorderThickness: CoreTokens.border_width_2,
  },
  wizard: {
    visitedStepFontColor: CoreTokens.color_black,
    visitedStepBackgroundColor: CoreTokens.color_white,
    visitedStepBorderColor: CoreTokens.color_black,
    unvisitedStepFontColor: CoreTokens.color_grey_700,
    unvisitedLabelFontColor: CoreTokens.color_grey_700,
    unvisitedHelperTextFontColor: CoreTokens.color_grey_700,
    unvisitedStepBackgroundColor: CoreTokens.color_transparent,
    unvisitedStepBorderColor: CoreTokens.color_grey_700,
    selectedStepFontColor: CoreTokens.color_white,
    selectedStepBackgroundColor: CoreTokens.color_purple_700,
    selectedStepBorderColor: CoreTokens.color_purple_700,
    selectedLabelFontColor: CoreTokens.color_black,
    selectedHelperTextFontColor: CoreTokens.color_black,
    selectedStepWidth: "32px",
    selectedStepHeight: "32px",
    selectedStepBorderThickness: "2px",
    selectedStepBorderStyle: CoreTokens.border_solid,
    selectedStepBorderRadius: "45px",
    stepFontSize: CoreTokens.type_scale_03,
    stepFontFamily: CoreTokens.type_sans,
    stepFontStyle: CoreTokens.type_normal,
    stepFontWeight: CoreTokens.type_regular,
    stepFontTracking: CoreTokens.type_spacing_wide_02,
    stepIconSize: "20px",
    stepWidth: "32px",
    stepHeight: "32px",
    stepBorderThickness: "2px",
    stepBorderStyle: CoreTokens.border_solid,
    stepBorderRadius: "45px",
    visitedLabelFontColor: CoreTokens.color_black,
    labelFontSize: CoreTokens.type_scale_03,
    labelFontFamily: CoreTokens.type_sans,
    labelFontStyle: CoreTokens.type_normal,
    labelFontWeight: CoreTokens.type_regular,
    labelFontTracking: CoreTokens.type_spacing_normal,
    labelFontTextTransform: "none",
    labelTextAlign: "left",
    helperTextFontSize: CoreTokens.type_scale_02,
    helperTextFontFamily: CoreTokens.type_sans,
    helperTextFontStyle: CoreTokens.type_normal,
    helperTextFontWeight: CoreTokens.type_regular,
    helperTextFontTracking: CoreTokens.type_spacing_normal,
    helperTextFontTextTransform: "none",
    visitedHelperTextFontColor: CoreTokens.color_black,
    helperTextTextAlign: "left",
    disabledStepBackgroundColor: CoreTokens.color_grey_100,
    disabledStepFontColor: CoreTokens.color_grey_500,
    disabledLabelFontColor: CoreTokens.color_grey_500,
    disabledHelperTextFontColor: CoreTokens.color_grey_500,
    disabledStepBorderColor: CoreTokens.color_grey_100,
    disabledStepWidth: "32px",
    disabledStepHeight: "32px",
    disabledStepBorderThickness: "2px",
    disabledStepBorderStyle: CoreTokens.border_solid,
    disabledStepBorderRadius: "45px",
    separatorBorderThickness: "1px",
    separatorBorderStyle: CoreTokens.border_solid,
    separatorColor: CoreTokens.color_grey_700,
    focusColor: CoreTokens.color_blue_600,
  },
};

export type AdvancedTheme = typeof componentTokens;

export type OpinionatedTheme = {
  accordion: {
    accentColor: string;
    titleFontColor: string;
    assistiveTextFontColor: string;
  };
  alert: {
    baseColor: string;
    accentColor: string;
    overlayColor: string;
  };
  box: {
    baseColor: string;
  };
  button: {
    baseColor: string;
    primaryFontColor: string;
    secondaryHoverFontColor: string;
  };
  checkbox: {
    baseColor: string;
    checkColor: string;
    fontColor: string;
  };
  chip: {
    baseColor: string;
    fontColor: string;
    iconColor: string;
  };
  dateInput: {
    baseColor: string;
    selectedFontColor: string;
  };
  dialog: {
    baseColor: string;
    closeIconColor: string;
    overlayColor: string;
  };
  dropdown: {
    baseColor: string;
    fontColor: string;
    optionFontColor: string;
  };
  fileInput: {
    fontColor: string;
  };
  footer: {
    baseColor: string;
    fontColor: string;
    accentColor: string;
    logo: string;
  };
  header: {
    baseColor: string;
    accentColor: string;
    fontColor: string;
    menuBaseColor: string;
    hamburguerColor: string;
    logo: string;
    logoResponsive: string;
    contentColor: string;
    overlayColor: string;
  };
  link: {
    baseColor: string;
  };
  navTabs: {
    baseColor: string;
    accentColor: string;
  };
  paginator: {
    baseColor: string;
    fontColor: string;
  };
  progressBar: {
    accentColor: string;
    baseColor: string;
    fontColor: string;
    overlayColor: string;
    overlayFontColor: string;
  };
  quickNav: {
    fontColor: string;
    accentColor: string;
  };
  radioGroup: {
    baseColor: string;
    fontColor: string;
  };
  select: {
    selectedOptionBackgroundColor: string;
    fontColor: string;
    optionFontColor: string;
    hoverBorderColor: string;
  };
  sidenav: {
    baseColor: string;
  };
  slider: {
    baseColor: string;
    fontColor: string;
    totalLineColor: string;
  };
  spinner: {
    accentColor: string;
    baseColor: string;
    fontColor: string;
    overlayColor: string;
    overlayFontColor: string;
  };
  switch: {
    checkedBaseColor: string;
    fontColor: string;
  };
  table: {
    baseColor: string;
    headerFontColor: string;
    cellFontColor: string;
  };
  tabs: {
    baseColor: string;
  };
  tag: {
    fontColor: string;
    iconColor: string;
  };
  textarea: {
    fontColor: string;
    hoverBorderColor: string;
  };
  textInput: {
    fontColor: string;
    hoverBorderColor: string;
  };
  toggleGroup: {
    selectedBaseColor: string;
    selectedFontColor: string;
    unselectedBaseColor: string;
    unselectedFontColor: string;
  };
  wizard: {
    baseColor: string;
    fontColor: string;
    selectedStepFontColor: string;
  };
};

export const spaces = {
  xxsmall: CoreTokens.spacing_4,
  xsmall: CoreTokens.spacing_8,
  small: CoreTokens.spacing_12,
  medium: CoreTokens.spacing_16,
  large: CoreTokens.spacing_24,
  xlarge: CoreTokens.spacing_32,
  xxlarge: CoreTokens.spacing_48,
};

export const responsiveSizes = {
  xsmall: "20",
  small: "30",
  medium: "45",
  large: "66",
  xlarge: "90",
};

export const defaultTranslatedComponentLabels = {
  formFields: {
    optionalLabel: "(Optional)",
    requiredSelectionErrorMessage: "This field is required. Please, choose an option.",
    requiredValueErrorMessage: "This field is required. Please, enter a value.",
    formatRequestedErrorMessage: "Please match the format requested.",
    lengthErrorMessage: (minLength?: number, maxLength?: number) => `Min length ${minLength}, max length ${maxLength}.`,
    logoAlternativeText: "Logo",
  },
  applicationLayout: {
    visibilityToggleTitle: "Toggle visibility sidenav",
  },
  alert: {
    infoTitleText: "information",
    successTitleText: "success",
    warningTitleText: "warning",
    errorTitleText: "error",
  },
  dateInput: {
    invalidDateErrorMessage: "Invalid date.",
  },
  dialog: {
    closeIconAriaLabel: "Close dialog",
  },
  fileInput: {
    fileSizeGreaterThanErrorMessage: "File size must be greater than min size.",
    fileSizeLessThanErrorMessage: "File size must be less than max size.",
    multipleButtonLabelDefault: "Select files",
    singleButtonLabelDefault: "Select file",
    dropAreaButtonLabelDefault: "Select",
    multipleDropAreaLabelDefault: "or drop files",
    singleDropAreaLabelDefault: "or drop a file",
    deleteFileActionTitle: "Remove file",
  },
  footer: {
    copyrightText: (year: number) => `© DXC Technology ${year}. All rights reserved.`,
  },
  header: {
    closeIcon: "Close menu",
    hamburguerTitle: "Menu",
  },
  numberInput: {
    valueGreaterThanOrEqualToErrorMessage: (value: number) => `Value must be greater than or equal to ${value}.`,
    valueLessThanOrEqualToErrorMessage: (value: number) => `Value must be less than or equal to ${value}.`,
    decrementValueTitle: "Decrement value",
    incrementValueTitle: "Increment value",
  },
  paginator: {
    itemsPerPageText: "Items per page: ",
    minToMaxOfText: (minNumberOfItems: number, maxNumberOfItems: number, totalItems: number) =>
      `${minNumberOfItems} to ${maxNumberOfItems} of ${totalItems}`,
    goToPageText: "Go to page:",
    pageOfText: (pageNumber: number, totalPagesNumber: number) => `Page: ${pageNumber} of ${totalPagesNumber}`,
  },
  passwordInput: {
    inputShowPasswordTitle: "Show password",
    inputHidePasswordTitle: "Hide password",
  },
  quickNav: {
    contentTitle: "Contents",
  },
  radioGroup: {
    optionalItemLabelDefault: "N/A",
  },
  select: {
    noMatchesErrorMessage: "No matches found",
    actionClearSelectionTitle: "Clear selection",
    actionClearSearchTitle: "Clear search",
  },
  tabs: {
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
  },
  textInput: {
    clearFieldActionTitle: "Clear field",
    searchingMessage: "Searching...",
    fetchingDataErrorMessage: "Error fetching data",
  },
  calendar: {
    daysShort: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    previousMonthTitle: "Previous month",
    nextMonthTitle: "Next month",
  },
};

export type TranslatedLabels = typeof defaultTranslatedComponentLabels;
