exports.componentsList = [
  { label: "Accordion", path: "/components/accordion", status: "ready" },
  { label: "Alert", path: "/components/alert", status: "ready" },
  {
    label: "Application Layout",
    path: "/components/application-layout",
    status: "ready",
  },
  {
    label: "Badge",
    path: "/components/badge",
    status: "experimental",
  },
  { label: "Bleed", path: "/components/bleed", status: "ready" },
  { label: "Box", path: "/components/box", status: "deprecated" },
  {
    label: "Bulleted List",
    path: "/components/bulleted-list",
    status: "ready",
  },
  { label: "Button", path: "/components/button", status: "ready" },
  { label: "Card", path: "/components/card", status: "ready" },
  { label: "Checkbox", path: "/components/checkbox", status: "ready" },
  { label: "Chip", path: "/components/chip", status: "ready" },
  { label: "Container", path: "/components/container", status: "experimental" },
  { label: "Date Input", path: "/components/date-input", status: "ready" },
  { label: "Dialog", path: "/components/dialog", status: "ready" },
  { label: "Divider", path: "/components/divider", status: "experimental" },
  { label: "Dropdown", path: "/components/dropdown", status: "ready" },
  { label: "File Input", path: "/components/file-input", status: "ready" },
  { label: "Flex", path: "/components/flex", status: "ready" },
  { label: "Footer", path: "/components/footer", status: "ready" },
  { label: "Grid", path: "/components/grid", status: "ready" },
  { label: "Header", path: "/components/header", status: "ready" },
  { label: "Heading", path: "/components/heading", status: "ready" },
  { label: "Image", path: "/components/image", status: "experimental" },
  { label: "Inset", path: "/components/inset", status: "ready" },
  { label: "Link", path: "/components/link", status: "ready" },
  { label: "Nav Tabs", path: "/components/nav-tabs", status: "ready" },
  { label: "Number Input", path: "/components/number-input", status: "ready" },
  { label: "Paginator", path: "/components/paginator", status: "ready" },
  { label: "Paragraph", path: "/components/paragraph", status: "ready" },
  {
    label: "Password Input",
    path: "/components/password-input",
    status: "ready",
  },
  { label: "Progress Bar", path: "/components/progress-bar", status: "ready" },
  { label: "Quick Nav", path: "/components/quick-nav", status: "ready" },
  { label: "Radio Group", path: "/components/radio-group", status: "ready" },
  {
    label: "Resultset Table",
    path: "/components/resultset-table",
    status: "ready",
  },
  { label: "Select", path: "/components/select", status: "ready" },
  { label: "Sidenav", path: "/components/sidenav", status: "ready" },
  { label: "Slider", path: "/components/slider", status: "ready" },
  { label: "Spinner", path: "/components/spinner", status: "ready" },
  {
    label: "Status Light",
    path: "/components/status-light",
    status: "experimental",
  },
  { label: "Switch", path: "/components/switch", status: "ready" },
  { label: "Table", path: "/components/table", status: "ready" },
  { label: "Tabs", path: "/components/tabs", status: "ready" },
  { label: "Tag", path: "/components/tag", status: "ready" },
  { label: "Text Input", path: "/components/text-input", status: "ready" },
  { label: "Textarea", path: "/components/textarea", status: "ready" },
  { label: "Toggle Group", path: "/components/toggle-group", status: "ready" },
  { label: "Typography", path: "/components/typography", status: "ready" },
  { label: "Wizard", path: "/components/wizard", status: "ready" },
];
