import { SVG } from "../common/utils";
import AvatarProps from "../avatar/types";

export type ChipAvatarType = {
  color: AvatarProps["color"];
  profileName?: AvatarProps["label"];
  imageSrc?: AvatarProps["imageSrc"];
  icon?: AvatarProps["icon"];
};

type Props = {
  /**
   * If true, the component will be disabled.
   */
  disabled?: boolean;
  /**
   * Text to be placed on the chip.
   */
  label: string;
  /**
   * Determines the visual style and functionality of the chip. Available modes are:
   * - "selectable": The whole chip is an interactive element that allows users to activate or clear options directly within the interface.
   * - "dismissible": Dismissible chip is used to represent information generated by user input within an interface.
   */
  mode?: "selectable" | "dismissible";
  /**
   * Function to be called when the chip is clicked or the dismiss action is triggered.
   */
  onClick?: () => void;
  /**
   * Element, path or avatar used as icon to be placed before the chip label.
   */
  prefix?: string | SVG | ChipAvatarType;
  /**
   * If true, the component will be selected. This property is only applicable when the mode is "selectable".
   * If undefined, the component manages its own internal state (uncontrolled mode).
   */
  selected?: boolean;
  /**
   * Value of the tabindex attribute.
   */
  tabIndex?: number;
};

export default Props;
