import { componentTokens } from "../common/variables";

export default {
  dropdown: {
    // ActionIcon size tokens
    buttonIconSize: "16px",
    buttonPaddingTop: "4px",
    buttonPaddingBottom: "4px",
    buttonPaddingLeft: "4px",
    buttonPaddingRight: "4px",
    buttonHeight: "24px",
    buttonBorderRadius: "2px",
    buttonBorderStyle: "none",
    buttonBorderThickness: "0px",
    buttonBorderColor: "transparent",
    optionFontSize: "14px",
    optionPaddingTop: "0px",
    optionPaddingBottom: "0px",
    optionPaddingLeft: "16px",
    optionPaddingRight: "16px",

    // Dropdown tokens
    buttonBackgroundColor: componentTokens.table.actionBackgroundColor,
    hoverButtonBackgroundColor: componentTokens.table.hoverActionBackgroundColor,
    activeButtonBackgroundColor: componentTokens.table.activeActionBackgroundColor,
    buttonFontFamily: componentTokens.dropdown.buttonFontFamily,
    buttonFontSize: componentTokens.dropdown.buttonFontSize,
    buttonFontStyle: componentTokens.dropdown.buttonFontStyle,
    buttonFontWeight: componentTokens.dropdown.buttonFontWeight,
    buttonFontColor: componentTokens.dropdown.buttonFontColor,
    buttonIconSpacing: componentTokens.dropdown.buttonIconSpacing,
    buttonIconColor: componentTokens.table.actionIconColor,
    disabledColor: componentTokens.table.disabledActionIconColor,
    disabledButtonBorderColor: componentTokens.dropdown.disabledButtonBorderColor,
    disabledButtonBackgroundColor: componentTokens.table.disabledActionBackgroundColor,
    disabledBorderColor: componentTokens.dropdown.disabledBorderColor,
    optionBackgroundColor: componentTokens.dropdown.optionBackgroundColor,
    hoverOptionBackgroundColor: componentTokens.dropdown.hoverOptionBackgroundColor,
    activeOptionBackgroundColor: componentTokens.dropdown.activeOptionBackgroundColor,
    optionFontFamily: componentTokens.dropdown.optionFontFamily,
    optionFontStyle: componentTokens.dropdown.optionFontStyle,
    optionFontWeight: componentTokens.dropdown.optionFontWeight,
    optionFontColor: componentTokens.dropdown.optionFontColor,
    optionIconSize: componentTokens.dropdown.optionIconSize,
    optionIconSpacing: componentTokens.dropdown.optionIconSpacing,
    optionIconColor: componentTokens.dropdown.optionIconColor,
    caretIconSize: componentTokens.dropdown.caretIconSize,
    caretIconColor: componentTokens.dropdown.caretIconColor,
    caretIconSpacing: componentTokens.dropdown.caretIconSpacing,
    borderRadius: componentTokens.dropdown.borderRadius,
    borderStyle: componentTokens.dropdown.borderStyle,
    borderThickness: componentTokens.dropdown.borderThickness,
    borderColor: componentTokens.dropdown.borderColor,
    scrollBarThumbColor: componentTokens.dropdown.scrollBarThumbColor,
    scrollBarTrackColor: componentTokens.dropdown.scrollBarTrackColor,
    focusColor: componentTokens.table.focusActionBorderColor,
  },
};
