import { componentTokens } from "../common/variables";
export default {
  dropdown: {
    // Breadcrumbs tokens
    buttonIconSize: "16px",
    buttonPaddingTop: "4px",
    buttonPaddingBottom: "4px",
    buttonPaddingLeft: "4px",
    buttonPaddingRight: "4px",
    buttonHeight: "24px",
    buttonBorderRadius: "2px",
    buttonBorderColor: "transparent",
    optionFontSize: "14px",
    optionPaddingTop: "0px",
    optionPaddingBottom: "0px",
    optionPaddingLeft: "16px",
    optionPaddingRight: "16px",

    // Dropdown tokens
    buttonBackgroundColor: componentTokens.table.actionBackgroundColor,
    hoverButtonBackgroundColor: componentTokens.table.hoverActionBackgroundColor,
    activeButtonBackgroundColor: componentTokens.table.activeActionBackgroundColor,
    buttonFontFamily: "Open Sans, sans-serif",
    buttonFontSize: "1rem",
    buttonFontStyle: "normal",
    buttonFontWeight: "400",
    buttonFontColor: "#000000",
    buttonIconSpacing: "10px",
    buttonIconColor: componentTokens.table.actionIconColor,
    disabledColor: componentTokens.table.disabledActionIconColor,
    disabledButtonBackgroundColor: componentTokens.table.disabledActionBackgroundColor,
    disabledBorderColor: "transparent",
    optionBackgroundColor: "#ffffff",
    hoverOptionBackgroundColor: "#f2f2f2",
    activeOptionBackgroundColor: "#cccccc",
    optionFontFamily: "Open Sans, sans-serif",
    optionFontStyle: "normal",
    optionFontWeight: "400",
    optionFontColor: "#000000",
    optionIconSize: "20px",
    optionIconSpacing: "10px",
    optionIconColor: "#000000",
    caretIconSize: "24px",
    caretIconColor: "#000000",
    caretIconSpacing: "12px",
    borderRadius: "4px",
    borderStyle: "none",
    borderThickness: "0px",
    borderColor: "transparent",
    scrollBarThumbColor: "#666666",
    scrollBarTrackColor: "#cccccc",
  },
};
