import CoreTokens from "../common/coreTokens";

export default {
  dropdown: {
    // Breadcrumbs tokens
    buttonIconSize: CoreTokens.spacing_16,
    buttonPaddingTop: CoreTokens.spacing_4,
    buttonPaddingBottom: CoreTokens.spacing_4,
    buttonPaddingLeft: CoreTokens.spacing_4,
    buttonPaddingRight: CoreTokens.spacing_4,
    buttonHeight: "24px",
    buttonBorderRadius: "2px",
    buttonBorderColor: CoreTokens.color_transparent,
    optionFontSize: "14px",
    optionPaddingTop: CoreTokens.spacing_0,
    optionPaddingBottom: CoreTokens.spacing_0,
    optionPaddingLeft: CoreTokens.spacing_16,
    optionPaddingRight: CoreTokens.spacing_16,

    // Dropdown tokens
    buttonBackgroundColor: CoreTokens.color_white,
    hoverButtonBackgroundColor: CoreTokens.color_grey_100,
    activeButtonBackgroundColor: CoreTokens.color_grey_300,
    buttonFontFamily: CoreTokens.type_sans,
    buttonFontSize: CoreTokens.type_scale_03,
    buttonFontStyle: CoreTokens.type_normal,
    buttonFontWeight: CoreTokens.type_regular,
    buttonFontColor: CoreTokens.color_black,
    buttonIconSpacing: "10px",
    buttonIconColor: CoreTokens.color_black,
    buttonBorderStyle: CoreTokens.border_none,
    buttonBorderThickness: CoreTokens.border_width_0,
    disabledColor: CoreTokens.color_grey_500,
    disabledButtonBackgroundColor: CoreTokens.color_transparent,
    disabledButtonBorderColor: CoreTokens.color_transparent,
    optionBackgroundColor: CoreTokens.color_white,
    hoverOptionBackgroundColor: CoreTokens.color_grey_100,
    activeOptionBackgroundColor: CoreTokens.color_grey_300,
    optionFontFamily: CoreTokens.type_sans,
    optionFontStyle: CoreTokens.type_normal,
    optionFontWeight: CoreTokens.type_regular,
    optionFontColor: CoreTokens.color_black,
    optionIconSize: "20px",
    optionIconSpacing: "10px",
    optionIconColor: CoreTokens.color_black,
    caretIconSize: "24px",
    caretIconColor: CoreTokens.color_black,
    caretIconSpacing: "12px",
    borderRadius: "4px",
    borderStyle: CoreTokens.border_none,
    borderThickness: CoreTokens.border_width_0,
    borderColor: CoreTokens.color_transparent,
    scrollBarThumbColor: CoreTokens.color_grey_700,
    scrollBarTrackColor: CoreTokens.color_grey_300,
    focusColor: CoreTokens.color_blue_600,
  },
};
