name: Publish Website

on:
  push:
    branches:
      - master
    paths:
      - "apps/website/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build library and website
        env:
          NEXT_PUBLIC_SITE_VERSION: next
        run: npm run build
