name: Publish Website

on:
  push:
    branches:
      - master
    paths:
      - "apps/website/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/

      - name: Deploy via SFTP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
        run: |
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/ssh_file.pem

          chmod 600 ~/.ssh/ssh_file.pem

          ssh-keyscan -H -p 22 $SFTP_HOST >> ~/.ssh/known_hosts

          sftp -i ~/.ssh/ssh_file.pem -b - $SFTP_USER@$SFTP_HOST <<EOF
          put -r ./apps/website/out/* halstack/next/
          EOF
